packages/core/package.json, packages/core/src/ElementsFactory/interfaces.ts, packages/core/src/elements/Popup/FePopup.scss, packages/core/src/elements/Popup/FePopup.tsx, packages/core/src/elements/Popup/Popup.tsx, packages/core/src/elements/Popup/PopupComponent.tsx, packages/core/src/elements/Popup/Tooltip.tsx, packages/core/src/elements/Popup/index.ts, packages/core/src/elements/Popup/interfaces.ts, packages/core/src/elements/index.ts, packages/demo-saas/src/App/App.tsx, packages/demo-saas/src/PopupExample.tsx, packages/elements-material-ui/package.json, packages/elements-material-ui/src/Popup/index.tsx, packages/elements-material-ui/src/Popup/style.scss, packages/elements-material-ui/src/index.ts, packages/elements-semantic/src/Popup/index.tsx, packages/elements-semantic/src/index.ts, yarn.lock
For the material UI lib, I used a third party library to have a suitable popup functionality.
I also use this library for the core library popup.
Lib: https://www.npmjs.com/package/react-popper-tooltip
=> Add popup element

.github/workflows/create-release-pr.yml, .github/workflows/publish.yml
- add option to COLLABORATOR to create release
- disable publish flow if pull-request not contains releaase version
=> Pull Request Workflow Fixes

.github/workflows/create-release-pr.yml, package.json
- remove unused steps
- add --conventional-graduate to lerna version
=> fix(ci): fix build bugs

.github/workflows/create-release-pr.yml, Makefile, package.json, packages/core/src/FronteggProvider.tsx, scripts/commit.js
- add backward compatibility for old frontegg react
- add cli commit helper
=> Build Improvments

packages/core/src/I18nInitializer/en.ts, packages/core/src/elements/Select/FeSelect.tsx, packages/demo-saas/src/SelectorExample.tsx, packages/elements-material-ui/src/Select/index.tsx, packages/elements-semantic/src/Select/Select.tsx, packages/elements-semantic/src/Select/index.ts, packages/elements-semantic/src/index.ts
Don't pay attention on accordions fiels it's because of prettier hook
=> Select element

packages/auth/package.json, packages/core/package.json
=> fix(packaging): add missing immer dependency

packages/demo-saas/src/App/App.tsx, packages/demo-saas/src/TableExample.tsx, packages/demo-saas/src/withFrontegg.tsx, packages/elements-material-ui/src/Table/Table.tsx, packages/elements-material-ui/src/Table/TableBody.tsx, packages/elements-material-ui/src/Table/TableHead.tsx, packages/elements-material-ui/src/Table/style.scss
Fix sort icon onhover, fix table header sticky
=> fix(elements): fix table material

packages/auth/src/Api/SSOState/index.ts, packages/auth/src/Api/SSOState/saga.ts, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPForm.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPPage.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPSteps.tsx, packages/auth/src/Team/TeamAddUserDialog.tsx, packages/auth/src/styles/sso.scss, packages/core/src/I18nInitializer/en.ts
I need to enable an account to work with sagas
In inputs don't present copy buttons
=> add formik for saml config, add auto config

packages/auth/src/Api/TeamState/index.ts, packages/auth/src/Team/TeamTable.tsx, packages/core/src/api/teams/index.ts, packages/core/src/api/teams/interfaces.ts, packages/core/src/elements/Button/FeButton.scss, packages/core/src/elements/Button/FeButton.tsx, packages/core/src/elements/Button/interfaces.ts, packages/elements-material-ui/src/Button/index.tsx
=> refactor(auth): add options with buttons resend activation and delete

packages/auth/src/Api/LoginState/index.ts, packages/auth/src/Api/LoginState/saga.ts, packages/auth/src/Api/TeamState/saga.ts, packages/auth/src/Api/initialState.ts, packages/auth/src/HOCs.tsx, packages/auth/src/Listener.tsx, packages/auth/src/Login/LoginWithTwoFactor.tsx, packages/auth/src/Login/Logout.tsx, packages/auth/src/Team/TeamTableCells.tsx, packages/auth/src/Team/TeamTableToolbar.tsx, packages/auth/src/components/AuthRoutes.tsx, packages/auth/src/index.ts, packages/core/src/components/PageHeader/PageHeader.tsx, packages/core/src/elements/Icon/FeIcon.tsx, packages/core/src/elements/Icon/interfaces.ts, packages/core/src/styles/mixin.scss, packages/demo-saas/src/withFrontegg.tsx, packages/elements-material-ui/src/Icon/index.tsx, packages/elements-material-ui/src/Input/index.tsx, packages/elements-semantic/src/Icon/index.tsx, packages/elements-semantic/src/Input/index.tsx, packages/elements-semantic/src/Input/style.scss
- fix session timeout
- fix heaader img bug in auth plugin options
- add back icon
=> fix(auth): bug fixes

packages/auth/src/Api/LoginState/saga.ts, packages/auth/src/Api/TeamState/saga.ts, packages/auth/src/Login/LoginWithPassword.tsx, packages/auth/src/tests/login-flow.cy-spec.tsx, packages/core/src/FronteggProvider.tsx, packages/core/src/elements/Button/interfaces.ts, packages/demo-saas/src/index.tsx
- feature: redirect user to login with two-factor after saml if required
- fix: multiple store initialization in strict-mode
- fix: remove last role in TeamTable
- fix: remain user data after editing roles in TeamTable
Resolves #99, resolves #101, resolves #103
=> Auth plugin fixes

packages/auth/src/SocialLogins/SocialLogins.tsx
fix social login loader after social login callback failed and user clicked on back to login button
=> fix(auth): fix social logins loader

packages/auth/src/Team/TeamTableCells.tsx, packages/auth/src/styles/common.scss, packages/auth/src/styles/team.scss
=> FR-797 Fix team management roles dropdown ui

packages/elements-material-ui/src/Popup/PopupClick.tsx
This was triggering for each row in the Team management table.
=> fix: Remove debugger line

packages/audits/src/components/Filter.tsx
add condition when a value of filter is undefined do not update filters state
=> fix(audits): fix cancel button on audits filter

packages/audits/src/components/styles.scss
=> fix(audits): display none cross btns in filters selectors material ui

packages/connectivity/src/components/ConnectivityForms/ConnectivitySlack.tsx, packages/connectivity/src/components/ConnectivityForms/ConnectivitySlackAuth.tsx, packages/connectivity/src/saga.ts
=> fix(connectivity): fix show platform if the it dosen't have any events

packages/core/src/elements/Popup/FePopup.tsx
=> fix(audits): FR-996 add closing popup when reference hidden 

packages/audits/src/components/AuditsTableIpCell.tsx, packages/audits/src/components/styles.scss, packages/core/src/elements/Icon/FeIcon.tsx, packages/core/src/elements/Icon/interfaces.ts, packages/core/src/elements/Icon/svgs/Close.tsx, packages/core/src/elements/Popup/FePopup.tsx, packages/demo-saas/src/pages/Icons.tsx, packages/elements-material-ui/src/Icon/index.tsx, packages/elements-material-ui/src/Popup/PopupClick.tsx, packages/elements-semantic/src/Icon/index.tsx
add the function closePopup using the imperative handler hook, now you can close the popup window without state control via ref
FR-999
[Demo](https://frontegg.atlassian.net/jira/software/c/projects/FR/issues/FR-999?jql=project%20%3D%20%22FR%22%20AND%20status%20IN%20%28%223%22%2C%20%221%22%29%20AND%20assignee%20IN%20%28currentUser%28%29%29%20ORDER%20BY%20status%20DESC)
=> fix(audits): FR-999 add x btn for ip popup

packages/connectivity/src/components/ConnectivityForms/ConnectivityForm.tsx, packages/connectivity/src/elements/InputEmailOrPhone.tsx, packages/connectivity/src/elements/MessgaeSlack.tsx, packages/connectivity/src/elements/SelectSlack.tsx, packages/connectivity/src/interfaces.ts, packages/elements-material-ui/src/InputChip/index.tsx, packages/elements-material-ui/src/InputChip/styles.scss
[FR-983](https://frontegg.atlassian.net/browse/FR-983)
[FR-985](https://frontegg.atlassian.net/browse/FR-985)
=> Fix connectivity

packages/auth/src/ApiTokens/components/ApiTokensDeleteDialog.tsx, packages/auth/src/styles/apiTokens.scss, packages/elements-material-ui/src/Dialog/style.scss
=> refactor(auth): Improve styles for material ui modals

packages/auth/src/ApiTokens/readme.md
=> docs(auth): add instruction how to hide created by user id column

packages/auth/src/Api/SSOState/index.ts, packages/auth/src/Api/SSOState/saga.ts, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPForm.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPGuide.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPGuideSteps.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPPage.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPSelect.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPSteps.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSODialogInstruction.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOVendors.tsx, packages/auth/src/SSO/helpers.ts, packages/core/src/I18nInitializer/en.ts, packages/rest-api/src/auth/interfaces.ts
FR-1106
Do not merge.
Waiting for the back-end.
=> refactor(auth): Refactor code, add handling logic for oidc SSO

packages/core/src/elements/InputChip/InputChip.tsx, packages/core/src/elements/InputChip/interfaces.ts
[FR-1107](https://frontegg.atlassian.net/browse/FR-1107)
=> fix(core): fix validate the InputChip component

packages/auth/src/Api/SSOState/index.ts, packages/auth/src/Api/SSOState/interfaces.ts, packages/auth/src/Api/SSOState/saga.ts, packages/auth/src/SSO/SSOManageAuthorizationPage/SSOManageAuthorizationForm.tsx, packages/auth/src/SSO/SSOManageAuthorizationPage/SSOManageAuthorizationPage.tsx, packages/auth/src/SSO/SSOManageAuthorizationPage/SSOManageAuthorizationSelect.tsx, packages/auth/src/SSO/SSOManageAuthorizationPage/index.ts, packages/auth/src/SSO/SSOOverviewPage/SSOStep.tsx, packages/auth/src/SSO/SSOOverviewPage/SSOSteps.tsx, packages/auth/src/SSO/SSORouter.tsx, packages/auth/src/SSO/index.ts, packages/auth/src/styles/sso.scss, packages/core/src/I18nInitializer/en.ts, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts
=> Sso authorization step

packages/core/src/elements/Popup/FePopup.tsx
https://frontegg.atlassian.net/browse/FR-1431
=> fix(core): fix close property for the FePopup component

packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPSelect.tsx, packages/auth/src/SSO/SSOConfigureIDPPage/SSOVendors.tsx
=> fix(auth): change oidc icon to correct

packages/auth/src/ApiTokens/components/ApiTokensHeader.tsx, packages/auth/src/ApiTokens/components/ApiTokensTableComponent.tsx, packages/auth/src/ApiTokens/components/ApiTokensTebleCell.tsx, packages/auth/src/ApiTokens/constants.ts, packages/core/src/I18nInitializer/en.ts, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts
=> refactor(auth): change user id to user name api tokens created by 

packages/auth/src/ActivateAccount/ActivateAccountForm.tsx, packages/auth/src/styles/socialLogins.scss
I removed margin because of this:
see google btn moved to the right
=> improvement(auth): add social logins on activate account form FR-1542

packages/auth/src/ApiTokens/components/ApiTokensTebleCell.tsx, packages/core/src/I18nInitializer/en.ts
=> refactor(auth): change data not found to user not found api tokens

packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksForm.tsx, packages/rest-api/src/connectivity/interfaces.ts
[FR-1467](https://frontegg.atlassian.net/browse/FR-1467)
=> FR-1467 fix secure key

packages/core/src/elements/Popup/FePopup.tsx
[FR-1540](https://frontegg.atlassian.net/browse/FR-1540) Portal/audits: ip pop up - X button is not working
=> fix(core): fix close tolltip popup

packages/connectivity/src/components/ConnectivityForms/ConnectivityForm.tsx, packages/core/src/elements/InputChip/InputChip.tsx
[FR-1607](https://frontegg.atlassian.net/browse/FR-1607) cannot add more then one phone number
=> FR-1607 cannot add more then one phone number 

packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksEdit.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksForm.tsx, packages/rest-api/src/connectivity/interfaces.ts
[FR-1467](https://frontegg.atlassian.net/browse/FR-1467) 
The empty value was changed from undefined to null.
=> FR-1467 fix secure key #2

packages/connectivity/src/styles/connectivity.scss, packages/connectivity/src/styles/content.scss, packages/connectivity/src/styles/panel.scss
=> fix(connectivity): fix icons on the list of platform

packages/core/src/elements/Table/FeTable.scss, packages/core/src/elements/Table/FeTable.tsx
[FR-1593](https://frontegg.atlassian.net/browse/FR-1593)
The video with how it works attached to the task.
=> feat(core): implement horizontal scrolling in the table component

packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksForm.tsx, packages/connectivity/src/elements/AccordingCategories.tsx, packages/connectivity/src/styles/content.scss, packages/connectivity/src/styles/panel.scss, packages/connectivity/src/styles/webhook.scss
=> Webhooks alignments

packages/audits/src/components/AuditsRawTable.tsx, packages/audits/src/components/AuditsSubHeader.tsx, packages/audits/src/components/AuditsTable.tsx, packages/audits/src/helpers/hooks.ts, packages/audits/src/index.ts, packages/core/src/elements/Table/FeTable.tsx, packages/rest-api/src/audits/interfaces.ts
[FR-1600](https://frontegg.atlassian.net/browse/FR-1600) audits - new added columns are not displayed
=> FR-1600 audits - new added columns are not displayed

packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksList.tsx
[FR-1836)](https://frontegg.atlassian.net/browse/FR-1836) Portal/webhooks: delete message disappears
=> FR-1836 delete dialog message disappears

packages/auth/src/Api/ProfileState/saga.ts
[FR-1760](https://frontegg.atlassian.net/browse/FR-1760)
=> FR-1760 fix(auth): fix caching photo in the profile page

packages/audits/src/components/AuditsTableIpCell.tsx, packages/core/src/components/TableCells.tsx
[FR-1874](https://frontegg.atlassian.net/browse/FR-1874) Sidekick/audits: remove "unknown" - leave empty
=> Fr 1874 remove unknown

packages/audits/src/helpers/filterHelper.ts
=> fix(audits): FR-1875 - changed time filter format

packages/audits/src/components/AuditsRawTable.tsx, packages/audits/src/helpers/str2bool.ts
https://user-images.githubusercontent.com/78534155/106907675-32399a80-6707-11eb-9a56-d2f89011107a.mov
fix
audits
added str2bool to filter show in more info
=> fix(audits): FR-1884: columns that shouldn't be in more info are displayed

packages/audits/src/components/AuditsTableCell.tsx, packages/audits/src/components/styles.scss
[FR-2033](https://frontegg.atlassian.net/browse/FR-2033) Audits - USER AGENT logo -  align logo and add pointer when hover
=> FR-2033 align icon and add cursor pointer on icons

packages/auth/src/SocialLogins/SocailLoginsSuccess.tsx, packages/auth/src/SocialLogins/hooks.ts, packages/auth/src/tests/login-flow.cy-spec.tsx, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts
Social logins redirect url value is being sent from the UI instead of the backend configuration
=> feat(auth): change social login redirect url behavior

packages/auth/src/Team/TeamTableCells.tsx, packages/core/src/elements/MenuItem/FeMenuItem.scss, packages/core/src/elements/MenuItem/FeMenuItem.tsx, packages/core/src/elements/MenuItem/interfaces.ts, packages/elements-material-ui/src/MenuItem/index.tsx
https://user-images.githubusercontent.com/54889005/111579652-11ad3780-87bf-11eb-8d8f-f75bbcf04f98.mov
=> fix: FR-2220 - add loader for MenuItem

packages/auth/src/ActivateAccount/ActivateAccount.tsx, packages/auth/src/ActivateAccount/ActivateAccountFailedRedirect.tsx, packages/auth/src/ActivateAccount/ActivateAccountResendEmail.tsx, packages/auth/src/Api/ActivateState/index.ts, packages/auth/src/Api/ActivateState/interfaces.ts, packages/auth/src/Api/ActivateState/saga.ts, packages/core/src/I18nInitializer/en.ts, packages/core/src/styles/helpers.scss, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts
https://user-images.githubusercontent.com/78534155/111148444-4f7a4800-8594-11eb-92cf-aa91553b7151.mov
=> feat(auth): request new activation email

packages/core/src/styles/helpers.scss
=> fix(core): FR-2126 - removed list dots for error message

packages/auth/package.json, packages/core/package.json, packages/core/src/FronteggProvider.tsx
Remove immutable check and add peerDependencies
=> fix: Fix build for rescript

packages/auth/src/Profile/ProfilePasswordSettingsPage/ProfilePasswordSettingsPage.tsx, packages/auth/src/components/FReCaptcha.tsx
=> fix(auth): fix fromik import in FeRecaptcha to prevent build fails

packages/connectivity/src/components/ConnectivityPanel.tsx, packages/connectivity/src/components/ConnectivityTable.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksEdit.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksForm.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksList.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksLog.tsx, packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksTestFrom.tsx
https://user-images.githubusercontent.com/54889005/113421084-2569b800-93d3-11eb-9b75-6bcef9c62b0c.mov
=> fix(connectivity): FR-2310 - fix test hook form filling

packages/auth/src/SocialLogins/FacebookLogin/FacebookIcon.tsx, packages/auth/src/SocialLogins/FacebookLogin/index.tsx, packages/auth/src/SocialLogins/SocialLogins.tsx, packages/auth/src/SocialLogins/SocialLoginsWithWrapper.tsx, packages/auth/src/styles/socialLogins.scss, packages/rest-api/src/auth/interfaces.ts
https://user-images.githubusercontent.com/78534155/113120714-89954c00-921a-11eb-83e6-c6badd7fc70f.mov
=> feat(auth): login with facebook account

packages/connectivity/src/components/ConnectivityWebhooks/ConnectivityWebhooksTestFrom.tsx, packages/core/src/styles/Styles.ts, packages/core/src/styles/colors.scss, packages/core/src/styles/mixin.scss, packages/elements-material-ui/src/Button/index.tsx, packages/elements-material-ui/src/Loader/index.tsx, packages/elements-material-ui/src/Tag/index.tsx, packages/elements-semantic/src/Tag/index.tsx
=> fix: FR-2312 - fixstyle status button (webhooks); add success for theme'

packages/auth/src/ActivateAccount/ActivateAccountForm.tsx
=> fix(auth): FR-2218 - remove social logins from activate user form

packages/core/src/elements/Table/FeTable.scss, packages/core/src/elements/Table/FeTableTHead.tsx, packages/elements-material-ui/src/Table/TableBody.tsx, packages/elements-material-ui/src/Table/TableHead.tsx
=> fix: FR-2100 - fix expandable table styles

packages/auth/src/SignUp/SignUpForm.tsx
https://user-images.githubusercontent.com/54889005/111439450-0cdc7b00-870e-11eb-888a-5c2b2df4b05e.mov
=> fix(auth): FR-2206 - add error message for sign up form

packages/redux-store/src/auth/saga.ts
=> fix: remove live sagas from mock generator function

packages/redux-store/src/auth/SecurityPolicyState/index.ts, packages/redux-store/src/auth/SecurityPolicyState/interfaces.ts, packages/redux-store/src/auth/SecurityPolicyState/saga.ts, packages/redux-store/src/auth/dummy.ts, packages/rest-api/src/auth/secutiry-poilicy/index.ts, packages/rest-api/src/auth/secutiry-poilicy/interfaces.ts
=> FR-2393 - add support for password history

packages/react-hooks/package.json, packages/react-hooks/rollup.config.js, packages/react-hooks/src/auth/hooks.ts
=> fix: Add react-redux to react-hooks dist file

packages/auth/src/SSO/SSOConfigureIDPPage/SSOConfigureIDPSteps.tsx
We have another destructurization on 18 string
=> fix(auth): remove duplicated useField destructure

packages/redux-store/src/audits/dummy.ts
=> feat: add random user for auditLogsDataDemo

packages/audits/src/components/AuditsTableCell.tsx, packages/audits/src/components/styles.scss
FR-2506 - Dashboard - the audit logs are failed
=> fix(audits): FR-2506 fix position and behaviors of the User Agent logo

packages/auth/src/Login/ForceEnrollMfa.tsx, packages/auth/src/Login/Login.tsx, packages/auth/src/Login/LoginWithTwoFactor.tsx, packages/auth/src/tests/login-flow.cy-spec.tsx, packages/core/src/I18nInitializer/en.ts, packages/redux-store/src/auth/ActivateState/saga.ts, packages/redux-store/src/auth/LoginState/index.ts, packages/redux-store/src/auth/LoginState/interfaces.ts, packages/redux-store/src/auth/LoginState/saga.ts, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts, packages/rest-api/src/constants.ts
https://user-images.githubusercontent.com/78534155/118639783-f2438280-b7e0-11eb-968c-6d30817e2294.mov
=> feat(auth): [FR-2731] remember MFA devices 

packages/connectivity/src/styles/connectivity.scss
Demo: https://frontegg.atlassian.net/browse/FR-3005?atlOrigin=eyJpIjoiOTUwNzRmM2ZiYmRiNGUxZjk1MjExZTAwMWRiZTQyMTEiLCJwIjoiaiJ9
This is the most suitable solution which I found. @davidantoon probably you have any idea how to do this better.
Sync with Royi to get more description about this issue
=> fix(connectivity): add overflow auto to connectivity page FR-3005

packages/connectivity/README.md, packages/connectivity/src/components/ConnectivityPage.tsx, packages/connectivity/src/styles/connectivity.scss
FR-3005 - Connectivity component overflowing
It's an example of how the component looks with the parameter **fitContent**:
https://user-images.githubusercontent.com/4667761/119110931-404bc680-ba2b-11eb-97ee-ebfa0a3771a4.mov
=> feat(connectivity): add new parameter fitContent

packages/auth/src/SignUp/SignUp.tsx, packages/auth/src/SignUp/SignUpForm.tsx, packages/auth/src/SocialLogins/FacebookLogin/index.tsx, packages/auth/src/SocialLogins/GithubLogin/index.tsx, packages/auth/src/SocialLogins/GoogleLogin/index.tsx, packages/auth/src/SocialLogins/MicrosoftLogin/index.tsx, packages/auth/src/SocialLogins/SocailLoginsSuccess.tsx, packages/auth/src/SocialLogins/SocialLoginButton.tsx, packages/auth/src/SocialLogins/SocialLogins.tsx, packages/auth/src/SocialLogins/SocialLoginsWithWrapper.tsx, packages/auth/src/SocialLogins/hooks.ts, packages/auth/src/SocialLogins/types.ts, packages/auth/src/styles/signUp.scss, packages/auth/src/styles/socialLogins.scss, packages/core/src/I18nInitializer/en.ts, packages/rest-api/src/auth/index.ts, packages/rest-api/src/auth/interfaces.ts
https://user-images.githubusercontent.com/49310486/119260543-efc79b00-bbdb-11eb-8243-9e86ee835a92.mov
=> feat(auth): force terms on social sign up FR-2869

packages/core/src/helpers/validates.ts
https://user-images.githubusercontent.com/78534155/119650969-20524380-be2d-11eb-83a6-2e372757b95d.mov
=> [FR-3076] refactor(core): increase domain suffix length to 20 chars

packages/redux-store/src/audits/AuditLogsState/saga.ts
Prev behaivour:
total = 23
pageSize = 20
totalPages => (total/pageSize).toFixed(0) =  1
Current behaviour:
total = 23
pageSize = 20
totalPages => Math.ceil(total/pageSize) =  2
=> fix: FR-3342, round number of total pages to bigger

packages/audits/src/Api/initialState.ts, packages/audits/src/Api/interfaces.ts, packages/audits/src/Api/reducer.ts, packages/audits/src/Api/saga.ts, packages/audits/src/components/Audits.tsx, packages/audits/src/components/AuditsRawTable.tsx, packages/audits/src/components/AuditsTable.tsx, packages/core/package.json, packages/core/src/elements/Table/FeTable.tsx, packages/core/src/elements/Table/FeTableTBody.tsx, packages/core/src/elements/Table/TableUtils.ts, packages/core/src/elements/Table/interfaces.ts, packages/core/src/interfaces/index.ts, packages/demo-saas/src/withFrontegg.tsx, packages/elements-material-ui/package.json, packages/elements-material-ui/src/Table/Table.tsx, packages/elements-material-ui/src/Table/TableBody.tsx, packages/elements-material-ui/src/Table/TableFilterColumn.tsx, packages/rest-api/src/audits/interfaces.ts, packages/rest-api/src/interfaces.ts
Didn't tested with 100-500+ items list
=> FR-3296: support virtual scroll audits/material-ui/core-ui

packages/react-hooks/src/subscriptions/hooks.ts, packages/redux-store/src/subscriptions/Checkout/index.ts, packages/redux-store/src/subscriptions/Checkout/interfaces.ts, packages/redux-store/src/subscriptions/Checkout/saga.ts, packages/redux-store/src/subscriptions/Config/index.ts, packages/redux-store/src/subscriptions/Config/interfaces.ts, packages/redux-store/src/subscriptions/Config/saga.ts, packages/rest-api/src/subscriptions/stripe/checkout.ts, packages/rest-api/src/subscriptions/stripe/interfaces.ts
Missing actions and state added
=> FR-2456 - Checkout Secret

packages/audits/src/Api/selectors.ts, packages/audits/src/components/AuditsListener.tsx, packages/audits/src/components/AuditsRawTable.tsx, packages/audits/src/components/renderExpandedComponent.tsx, packages/audits/src/helpers/hooks.ts, packages/audits/src/index.ts, packages/connectivity/src/components/ConnectivityForms/ConnectivitySlack.tsx, packages/core/src/helpers/FormikAutoSave.tsx, packages/elements-material-ui/src/Select/index.tsx
[FR-3651](https://frontegg.atlassian.net/browse/FR-3651) - Connectivity is sending ~300 fetch requests for slack configuration
[FR-3907](https://frontegg.atlassian.net/browse/FR-3907) - Admin/Connectivity: Enabling events in slack channel not sending requests
=> FR-3651 & FR-3907 the slack configuration - fixes problems

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- v3.14.0
- FR-3944 - added logs tp debug in prod
- FR-3795 - custom text to signUp switch
=> Update Frontegg AdminPortal to 3.14.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 4.14.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 4.18.1

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-4827](https://frontegg.atlassian.net/browse/FR-4827) - fix submit on enter with new slotted input - [5772c4c0](https://github.com/frontegg/admin-box/pulls?q=5772c4c0)
- [FR-4755](https://frontegg.atlassian.net/browse/FR-4755) - fix after signup redirect url on social login - [f45b025c](https://github.com/frontegg/admin-box/pulls?q=f45b025c)
- [FR-4761](https://frontegg.atlassian.net/browse/FR-4761) - 1. make input error optional, 2. make override of login pag… - [156d4021](https://github.com/frontegg/admin-box/pulls?q=156d4021)
- [FR-4770](https://frontegg.atlassian.net/browse/FR-4770) - fixed recaptcha bug - [2082ce84](https://github.com/frontegg/admin-box/pulls?q=2082ce84)
=> Update Frontegg AdminPortal to 4.40.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-4828](https://frontegg.atlassian.net/browse/FR-4828) - activate recaptcha - [8ec0e5c0](https://github.com/frontegg/admin-box/pulls?q=8ec0e5c0)
=> Update Frontegg AdminPortal to 4.40.1

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-5171](https://frontegg.atlassian.net/browse/FR-5171) - load sso configs fix - [5a294717](https://github.com/frontegg/admin-box/pulls?q=5a294717)
=> Update Frontegg AdminPortal to 5.4.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-5171](https://frontegg.atlassian.net/browse/FR-5171) - load sso configs fix - [0aa14437](https://github.com/frontegg/admin-box/pulls?q=0aa14437)
=> Update Frontegg AdminPortal to 5.5.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.7.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-4356](https://frontegg.atlassian.net/browse/FR-4356) - extract delete dialog - [4d984bdf](https://github.com/frontegg/admin-box/pulls?q=4d984bdf)
=> Update Frontegg AdminPortal to 5.8.2

packages/react/src/FronteggProvider.tsx, packages/react/src/routerProxy.tsx
Check if react router exists in v6 by using useInRouterContext hook and then will check if useNavigation exist
=> Fix render without router in v6

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-5345](https://frontegg.atlassian.net/browse/FR-5345) - add option to custom error in input - [9b6ebbf3](https://github.com/frontegg/admin-box/pulls?q=9b6ebbf3)
=> Update Frontegg AdminPortal to 5.11.0

package.json, packages/auth/package.json, packages/auth/src/constants.ts, packages/auth/src/tests/login-flow.cy-spec.tsx, packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-5712](https://frontegg.atlassian.net/browse/FR-5712) - fix text align in magic link - [1719e3b7](https://github.com/frontegg/admin-box/pulls?q=1719e3b7)
- [FR-4887](https://frontegg.atlassian.net/browse/FR-4887) - button should be disabled before user enters text - [fb61773e](https://github.com/frontegg/admin-box/pulls?q=fb61773e)
- [FR-4944](https://frontegg.atlassian.net/browse/FR-4944) - use accessible label for MFA checkbox - [fc4b3a37](https://github.com/frontegg/admin-box/pulls?q=fc4b3a37)
- [FR-4845](https://frontegg.atlassian.net/browse/FR-4845) - fix mfa error message - [ade49262](https://github.com/frontegg/admin-box/pulls?q=ade49262)
- [FR-5127](https://frontegg.atlassian.net/browse/FR-5127) - fix chip and placeholder styles in dark mode theme - …
=> Update Frontegg AdminPortal to 5.12.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-5567](https://frontegg.atlassian.net/browse/FR-5567) - cypress for test login with social login flow - [ea921fae](https://github.com/frontegg/admin-box/pulls?q=ea921fae)
- [FR-4870](https://frontegg.atlassian.net/browse/FR-4870) - fix webhooks table - [e6de3f46](https://github.com/frontegg/admin-box/pulls?q=e6de3f46)
- [FR-5572](https://frontegg.atlassian.net/browse/FR-5572) - make the test id correct - [ecce902e](https://github.com/frontegg/admin-box/pulls?q=ecce902e)
- [FR-5571](https://frontegg.atlassian.net/browse/FR-5571) - add better data test id to table - [a0d751a1](https://github.com/frontegg/admin-box/pulls?q=a0d751a1)
- [FR-5570](https://frontegg.atlassian.net/browse/FR-5570) - create mock for personal tokens - [7752861d](https://github.com/frontegg/admin-box/pulls?q=77528 …
=> Update Frontegg AdminPortal to 5.13.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.18.1

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-6007](https://frontegg.atlassian.net/browse/FR-6007) - Success activate screen should be shown also when MFA is forced - [d05be180](https://github.com/frontegg/admin-box/pulls?q=d05be180)
=> Update Frontegg AdminPortal to 5.19.0

packages/react/rollup.config.js, packages/react/src/FronteggProvider.tsx, packages/react/src/queryKeeper.tsx
Demo 
https://frontegg.atlassian.net/browse/FR-5727
Do not merge need to discuss some points
=> FR-5727 - add query keeper feature

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- 
- [FR-5234](https://frontegg.atlassian.net/browse/FR-5234) - improve login box UI - [fe7ea1be](https://github.com/frontegg/admin-box/pulls?q=fe7ea1be)
=> Update Frontegg AdminPortal to 5.21.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.25.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-6982](https://frontegg.atlassian.net/browse/FR-6982) - Update README.md - [5797fafd](https://github.com/frontegg/admin-box/pulls?q=5797fafd)
=> Update Frontegg AdminPortal to 5.34.1

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-7236](https://frontegg.atlassian.net/browse/FR-7236) - add more values to user activated event - [772e24c3](https://github.com/frontegg/admin-box/pulls?q=772e24c3)
=> Update Frontegg AdminPortal to 5.43.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-7706](https://frontegg.atlassian.net/browse/FR-7706) - checkout dialog app remove plan selection - [8cf0a2c2](https://github.com/frontegg/admin-box/pulls?q=8cf0a2c2)
=> Update Frontegg AdminPortal to 5.53.2

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-7659](https://frontegg.atlassian.net/browse/FR-7659) - Social login layout customization - [e4a8bb1d](https://github.com/frontegg/admin-box/pulls?q=e4a8bb1d)
=> Update Frontegg AdminPortal to 5.57.1

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - remove framer motion - [adacedfc](https://github.com/frontegg/admin-box/pulls?q=adacedfc)
=> Update Frontegg AdminPortal to 5.59.0

packages/core/package.json, packages/nextjs/package.json, packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.61.1

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.70.0

packages/react/package.json, yarn.lock
- [FR-8206](https://frontegg.atlassian.net/browse/FR-8206) - Subscriptions Downgrade Upgrade Option - [55238dd6](https://github.com/frontegg/admin-box/pulls?q=55238dd6)
=> Update Frontegg AdminPortal to 5.72.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 5.72.1

packages/react/package.json, yarn.lock
- [FR-8454](https://frontegg.atlassian.net/browse/FR-8454) - fix dialog size - [6a27838a](https://github.com/frontegg/admin-box/pulls?q=6a27838a)
=> Update Frontegg AdminPortal to 5.72.2

packages/react/package.json, yarn.lock
- [FR-8679](https://frontegg.atlassian.net/browse/FR-8679) - fix pii data on local storage - [8a8d1085](https://github.com/frontegg/admin-box/pulls?q=8a8d1085)
=> Update Frontegg AdminPortal to 5.78.1

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.7.0

packages/react/package.json, yarn.lock
- [FR-8900](https://frontegg.atlassian.net/browse/FR-8900) - add customization tests - [a0021c08](https://github.com/frontegg/admin-box/pulls?q=a0021c08)
- [FR-9007](https://frontegg.atlassian.net/browse/FR-9007) - move all related tests - [e1afb64c](https://github.com/frontegg/admin-box/pulls?q=e1afb64c)
- [FR-9066](https://frontegg.atlassian.net/browse/FR-9066) - prettify login tests - [4ff8d19b](https://github.com/frontegg/admin-box/pulls?q=4ff8d19b)
- [FR-9043](https://frontegg.atlassian.net/browse/FR-9043) - accept invitation test - [f30ac345](https://github.com/frontegg/admin-box/pulls?q=f30ac345)
- [FR-9065](https://frontegg.atlassian.net/browse/FR-9065) - add test activate account custom theme - [b1e50e85](https://github.com/frontegg/admin-box/pulls?q=b1e50e85)
- …
=> Update Frontegg AdminPortal to 6.32.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.33.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.34.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.36.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.41.0

packages/react/package.json, yarn.lock
- FR-9969 - fix getBaseUrl never returns context prefix
- FR-9927 - fix validation invite with bulk
=> Update Frontegg AdminPortal to 6.50.0

packages/react/package.json, yarn.lock
- FR-10010 - mfa fixes
- FR-9932 - Subscriptions billing collection
- FR-9526 - remove adding class to body when frontegg loading on nextjs
- FR-9977 - change validations + color in autofill mode
- FR-9971 - otc mobile fix
- FR-9821 - SCIM
=> Update Frontegg AdminPortal to 6.51.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.53.0

package.json, packages/react/rollup.config.js, packages/react/src/FronteggProvider.tsx, yarn.lock
Use CustomComponentRegister to allow hooks for custom components and adjust rollup config
=> FR-5607 - use CustomComponentRegister

packages/react/package.json, yarn.lock
- FR-10047 - fix bad UI webhook
- FR-9993 - Add custom event to add user by bulk
- FR-10118 - fix apple logo color change when font color changes
- FR-9976 - refactor otc
=> Update Frontegg AdminPortal to 6.54.0

packages/react/package.json, yarn.lock
- FR-9983 - make sure that OTC fields are in one column with submit button
- FR-9642 - Logout on OAuth service on Hosted Login
- FR-8022 - support linkedin
- FR-10212 - hide disabled cards from mfa list
=> Update Frontegg AdminPortal to 6.56.0

packages/react/package.json, yarn.lock
- FR-9413 - fix main login validation for on boarding
- FR-10241 - added support for redirectUrl on prelogin
- FR-10240 - remove linkedin from inactive providers
=> Update Frontegg AdminPortal to 6.57.0

packages/react/package.json, yarn.lock
- FR-10275 - Avoid calling conditioned hook in Google onetap code
=> Update Frontegg AdminPortal to 6.58.0

packages/react/package.json, yarn.lock
- FR-10248 - add spacing to mfa
- FR-10256 - replace apple button redirect url
- FR-10248 - add tooltip for card list item
- FR-10246 - Add impersonation indication in login session table
=> Update Frontegg AdminPortal to 6.59.0

packages/react/package.json, yarn.lock
- FR-8329 - roles mock
- FR-10141 - Added support for logout on hosted login in nextjs
- FR-9816 - Add Snyk to PR check whitelist
- FR-10345 - add margin login error
- FR-10330 - fixes for bulk
- FR-9816 - Fix branch selection
- 
- FR-10112 - update admin box pipeline angular
- FR-10141 - update rest-api
- FR-9816 - fix version
=> Update Frontegg AdminPortal to 6.64.0

packages/react/package.json, yarn.lock
- FR-10261 - fix sign up position in dark theme
- FR-10369 - change mfa ff name
=> Update Frontegg AdminPortal to 6.65.0

packages/react/package.json, yarn.lock
- FR-10549 - fix error login with sms
- FR-10437 - select color
- FR-10518 - fix client id not show in model
=> Update Frontegg AdminPortal to 6.69.0

packages/react/package.json, yarn.lock
- FR-10431 - input component for adding members
- FR-10414 - fix filter SSO providers according to the vendor choice
- FR-10430 - user groups card header
- FR-9271 - hosted login improvements
=> Update Frontegg AdminPortal to 6.70.0

packages/react/package.json, yarn.lock
- FR-10682 - change m2m strategy to be from identity
- FR-10660 - ui for prompt passkeys
=> Update Frontegg AdminPortal to 6.72.0

packages/react/package.json, yarn.lock
- FR-11025 - fix invite users bug
- FR-11009 - add support for new social login flow
=> Update Frontegg AdminPortal to 6.76.0

packages/react/package.json, yarn.lock
- FR-9524 - Add missing RecaptchaTokens, Fix first load recaptcha
- FR-9524 - Update packages folder path in nextjs project
- FR-11009 - fix auth url default value for preview mode
- FR-11009 - add check for social config authorization url validity
- FR-10428 - fix rest-api imports
- FR-11022 - groups feature bugfix
- FR-9524 - Fix Recaptcha
- FR-10945 - add passkeys privacy page
=> Update Frontegg AdminPortal to 6.77.0

packages/react/package.json, yarn.lock
- FR-9469 - Added support for customized social login providers
=> Update Frontegg AdminPortal to 6.78.0

packages/react/package.json, yarn.lock
- FR-10976 - Remove idle session export from default items
=> Update Frontegg AdminPortal to 6.80.0

packages/react/package.json, yarn.lock
- FR-11247 - fix version branch 6.82
=> Update Frontegg AdminPortal to 6.83.0

packages/react/package.json, yarn.lock
- FR-11248 - add the option to separate first and last name in sign up form
- FR-11354 - allaccounts components
=> Update Frontegg AdminPortal to 6.85.0

packages/react/package.json, yarn.lock
- FR-11389 - Fix activate account button disable/loading state
=> Update Frontegg AdminPortal to 6.87.0

packages/react/src/FronteggProvider.tsx
preserve queryParam if isAuthRoute
=> FR-11351 - preserve-query-params-for-login-per-tenant 

packages/react/package.json, yarn.lock
- FR-11479 - Passkeys button style should be the same configuration as "social login button" style
- FR-11375 - fix a11y login-box second part
=> Update Frontegg AdminPortal to 6.91.0

packages/react/package.json, yarn.lock
- FR-11551 - fix hover input eye icon button
- FR-11547 - fix a11y second part
=> Update Frontegg AdminPortal to 6.92.0

packages/react/package.json, yarn.lock
- FR-11564 - Social login button shouldn't inherit from secondary color
=> Update Frontegg AdminPortal to 6.94.0

.github/CODEOWNERS
[Issue](https://frontegg.atlassian.net/browse/FR-11632)
=> FR-11632 - update CODEOWNERS.md

packages/react/package.json, yarn.lock
- FR-11632 - update code owners
- FR-11581 - a11y login box onenter event
- FR-11353 - all accounts tree graph component
=> Update Frontegg AdminPortal to 6.95.0

packages/react/package.json, yarn.lock
- FR-11529 - fix bug white borders dark mode
- FR-11769 - add meta data to context
=> Update Frontegg AdminPortal to 6.99.0

packages/react/package.json, yarn.lock
- FR-11887 - Revert Entitlements SDK - Load entitlements list & make the data accessible for the wrappers"
=> Update Frontegg AdminPortal to 6.102.0

packages/react/package.json, yarn.lock
- FR-11482 - add CustomComponentRegister to admin box to prevent duplicated code in react and next js
- FR-10891 - fix space in input component
- FR-11734 - MSP - all accounts main page
- FR-11941 - Tests for login per tenant self service
- FR-11658 - create iframe login preview for login per tenant self service
=> Update Frontegg AdminPortal to 6.104.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.109.0

packages/react/package.json, yarn.lock
- FR-12313 - update load tenants to new version
- FR-12161 - msp bugfix, improvements
=> Update Frontegg AdminPortal to 6.112.0

packages/react/package.json, yarn.lock
- FR-12313 - remove useWorkspace from lerna.json
- FR-12313 - fix cdn
- FR-12313 - add logs to wait-for-cdn script
- FR-12287 - msp bugfix
=> Update Frontegg AdminPortal to 6.113.0

packages/react/package.json, yarn.lock
- FR-12405 - msp bugfix, improvements
- FR-12381 - users table v2 msp bugfix
=> Update Frontegg AdminPortal to 6.114.0

packages/react/package.json, yarn.lock
- FR-12277 - active tenant gap fix
=> Update Frontegg AdminPortal to 6.115.0

packages/react/package.json, yarn.lock
- FR-12426 - msp visibility bypermissions
- FR-12413 - fix msp accounts update
- FR-12213 - add security login flows - mfa and breached password
=> Update Frontegg AdminPortal to 6.116.0

packages/react/package.json, yarn.lock
- FR-12586 - Fix pipeline
- [FR-12581 - add support for custom inline html and script]
- [FR-12343 - admin box implement sso per tenant]
- [FR-12488 - users page load users support v1 and v2]
-  [FR-12164 - MSP bulk user invitation]
- [FR-12479 - msp fix warning dialog issue]
- [FR-12408 - entitlements redesign]
=> Update Frontegg AdminPortal to 6.118.0

packages/react/package.json, yarn.lock
- FR-12701 - revert change settings list
- FR-12696 - Entitlements load on demand fix
- FR-12701 - implememt sessions inner page
=> Update Frontegg AdminPortal to 6.124.0

packages/react/package.json, yarn.lock
- FR-12828 - entitlements api response change
- FR-12224 - support custom login for authenticated users without a tenant alias
=> Update Frontegg AdminPortal to 6.126.0

packages/demo-saas/src/index.tsx, packages/react/src/FronteggProvider.tsx
=> FR-12986 - report React version

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 6.134.0

packages/react/package.json, yarn.lock
- FR-13455 - Fixed impersonation with custom login on embedded initial blank screen
- FR-13649 - Fixed testimonial quote layout for split signup mode
=> Update Frontegg AdminPortal to 6.143.0

packages/react/package.json, yarn.lock
- FR-13665 - Enhance hasPermission with inEntitled in admin portal in case entitlements is enabled
=> Update Frontegg AdminPortal to 6.144.0

packages/react/package.json, yarn.lock
- FR-13364 - Improved validations text for sign in form
- FR-13737 - Changed breached password page to be shown just for block breached password policy
- FR-13665 - Enhance hasPermission with inEntitled in admin portal in case entitlements is enabled
=> Update Frontegg AdminPortal to 6.145.0

packages/react/package.json, yarn.lock
- FR-13798 - Added support for login with SMS
=> Update Frontegg AdminPortal to 6.146.0

packages/react/package.json, yarn.lock
- FR-13772 - Fixed issue on edit user roles modal - at least 1 role is required
- FR-13808 - Support Login with SMS
- FR-13786 - Support tab per tenant
=> Update Frontegg AdminPortal to 6.147.0

packages/react/package.json, yarn.lock
- FR-13508 - Mobile native module bridge
=> Update Frontegg AdminPortal to 6.148.0

packages/react/package.json, yarn.lock
- FR-14000 - Fix time zone
- FR-13834 - rule based entitlements - upgrade entitlements lib
- FR-13327 - update modern theme grey palette
- FR-13834 - Added Rule based entitlements
=> Update Frontegg AdminPortal to 6.151.0

packages/react/package.json, yarn.lock
- FR-14102 - Fixed entitlements Frontegg user-id attribute usage 
- FR-13123 - Added support to provide scopes for social logins
=> Update Frontegg AdminPortal to 6.152.0

packages/react/package.json, yarn.lock
- FR-13913 - Let tenants&#x2F;users set expiry on client credentials API tokens
- FR-14099 - Fix load custom login routes only when necessary
- FR-13605 - Support adding phone number field to signup page and control his required state
=> Update Frontegg AdminPortal to 6.153.0

packages/react/package.json, yarn.lock
- FR-14201 - Fixed login with SMS resend code action
=> Update Frontegg AdminPortal to 6.154.0

packages/react/package.json, yarn.lock
- FR-14324 - Fixed Hosted login race condition in Angular and supported prompt login with silent refresh
=> Update Frontegg AdminPortal to 6.155.0

packages/react/package.json, yarn.lock
- FR-14237 - Fix direct action with basename
=> Update Frontegg AdminPortal to 6.156.0

.github/workflows/push.yml, babel.config.js, package.json, packages/react/src/FronteggProvider.spec.tsx, packages/react/src/QueeryKeeper.spec.tsx, packages/react/tsconfig.json, packages/sanity-check/App.test.tsx, tsconfig.json, yarn.lock
Add jest and test for query keeper logic
=> FR-14174 - add-jest-testing-to-frontegg-react-sdk

packages/react/package.json, yarn.lock
- FR-14308 - Fixed alignment issue with icon in custom social login button
=> Update Frontegg AdminPortal to 6.158.0

packages/react/package.json, yarn.lock
- FR-14287 - Fix grammar of 1 day expiry of api tokens
=> Update Frontegg AdminPortal to 6.159.0

packages/react/package.json, yarn.lock
- FR-14324 - Fix android native module and add option for direct social login
=> Update Frontegg AdminPortal to 6.160.0

packages/react/package.json, yarn.lock
- FR-14219 - Step up - Embedded flow
- FR-14324 - Fix direct login custom social login
=> Update Frontegg AdminPortal to 6.163.0

packages/react/package.json, yarn.lock
- FR-14644 - Fixed enroll authenticator app missing error message when code is wrong
=> Update Frontegg AdminPortal to 6.164.0

packages/react/package.json, yarn.lock
- FR-14228 - Added Step Up feature to allow a second layer of authentication for sensitive actions
- FR-14578 - Fixed custom login without tenant alias
- FR-14638 - Missing exp on user interface
- FR-14560 - added temporary users feature
=> Update Frontegg AdminPortal to 6.166.0

packages/react/package.json, yarn.lock
- FR-14753 - Fixed step up key removing when user doesn&#39;t finish step up flow
=> Update Frontegg AdminPortal to 6.167.0

packages/react/package.json, yarn.lock
- FR-14807 - Fixed step up double call to generate step up session
=> Update Frontegg AdminPortal to 6.168.0

packages/react/package.json, yarn.lock
- FR-14813 - Fix texts in open app
- FR-14813 - Support mobile deep link redirect page
=> Update Frontegg AdminPortal to 6.170.0

packages/react/package.json, yarn.lock
- FR-14813 - Add support for open app page with basename
=> Update Frontegg AdminPortal to 6.171.0

packages/react/package.json, yarn.lock
- FR-14855 - Add support for social login consent, by default it&#39;s false.
=> Update Frontegg AdminPortal to 6.172.0

packages/react/package.json, yarn.lock
- FR-14197 - Added Canada to MFA sms list of countries
- FR-14859 - fix roles filtering for MSP
=> Update Frontegg AdminPortal to 6.173.0

packages/react/package.json, yarn.lock
- FR-14910 - Fixed handling entitlements errors 
- FR-14740 - Send tenant alias for hosted custom login auth user
=> Update Frontegg AdminPortal to 6.175.0

packages/react/package.json, yarn.lock
- FR-15087 - Added oidc support for linkedin
- FR-14997 - Fixed invite user dialog UI issues
=> Update Frontegg AdminPortal to 6.176.0

packages/react/package.json, yarn.lock
- FR-15100 - Fix Apple custom SSO scopes
=> Update Frontegg AdminPortal to 6.177.0

packages/react/package.json, yarn.lock
- FR-15305 - Fixed changed fields sent on edit group to support SCIM group update
- FR-15219 - Fixed missing row actions in users table when using MSP
=> Update Frontegg AdminPortal to 6.180.0

packages/react/package.json, yarn.lock
- FR-15376 - fixed null group description exception
=> Update Frontegg AdminPortal to 6.181.0

packages/react/package.json, yarn.lock
- FR-15270 - Added new roles page to the Admin Portal
- FR-15395 - Fixed tab tenant not cleared after logout
=> Update Frontegg AdminPortal to 6.182.0

packages/react/package.json, yarn.lock
- FR-13828 - Add option to specify prompt consent from loginDirectAction
- FR-15315 - Added sort for role selections in Admin Portal
=> Update Frontegg AdminPortal to 6.183.0

packages/react/package.json, yarn.lock
- FR-15233 - Fixed autocomplete popper
=> Update Frontegg AdminPortal to 6.184.0

packages/react/package.json, yarn.lock
- FR-15367 - Fixed user logo upload for SCIM users
- FR-15111 - Fixed impersonation embedded redirection
=> Update Frontegg AdminPortal to 6.186.0

packages/react/package.json, yarn.lock
- FR-15863 - Improved chip list design in admin portal
=> Update Frontegg AdminPortal to 6.187.0

packages/react/package.json, yarn.lock
- FR-16088 - Hosted portal from frontegg app (supoport angular and vanilla)
=> Update Frontegg AdminPortal to 6.189.0

packages/react/package.json, yarn.lock
- FR-15737 - Added an option for accounts to open sub-account management for their sub-accounts
- FR-15603 - Support embedded SCIM guides
=> Update Frontegg AdminPortal to 6.190.0

packages/react/package.json, yarn.lock
- FR-16463 - Removed domain restrictions validation when invite user from All Accounts page
- FR-16421 - Fixed error handling in edit phone number dialog
=> Update Frontegg AdminPortal to 6.194.0

packages/react/package.json, yarn.lock
- FR-16341 - Support hiding columns in admin portal users table
=> Update Frontegg AdminPortal to 6.195.0

packages/react/package.json, yarn.lock
- FR-16513 - Show client id on all tokens in API tokens table
=> Update Frontegg AdminPortal to 6.196.0

packages/react/package.json, yarn.lock
FR-15484 - Fix update tenant state after account settings change
FR-16613 - Add automatic sub-account access in MSP
=> Update Frontegg AdminPortal to 6.199.0

packages/react/package.json, yarn.lock
- FR-16704 - fix password meter unsuspended async component
=> Update Frontegg AdminPortal to 6.200.0

packages/react/package.json, yarn.lock
- FR-16737 - Allow terms and conditions checkbox on sign up form being optional
=> Update Frontegg AdminPortal to 6.202.0

packages/react/package.json, yarn.lock
- FR-16987 - Add additional params to vanilla js loginWithRedircet
- FR-16960 - Fix typography color in SSO guides dark mode
=> Update Frontegg AdminPortal to 6.203.0

packages/react/package.json, yarn.lock
* FR-17055 - Fix SSO redirect race condition
=> Update Frontegg AdminPortal to 6.205.0

packages/react/package.json, yarn.lock
- FR-17009 - Add the option to disable&#x2F;enable users from users table
=> Update Frontegg AdminPortal to 6.206.0

packages/react/package.json, yarn.lock
- FR-16990 - Fixed social logins container styling
- FR-17117 - Added URL validation to direct login action
=> Update Frontegg AdminPortal to 6.207.0

packages/react/package.json, yarn.lock
- FR-17169 - Added support in send unlock account email
=> Update Frontegg AdminPortal to 7.3.0

packages/react/package.json, yarn.lock
- FR-17531 - Prevent loading embedded views while hosted login is true
=> Update Frontegg AdminPortal to 7.4.0

packages/react/package.json, yarn.lock
- FR-17626 - Fix clientId on request authorize for multi-apps
- FR-17182 - Fix copy invite user link in hosted admin portal
=> Update Frontegg AdminPortal to 7.6.0

packages/react/package.json, yarn.lock
- FR-17443 - Fix infinite loader when using direct login action
=> Update Frontegg AdminPortal to 7.8.0

packages/react/package.json, yarn.lock
- FR-17649 - Fix autofill sms code iOS SDK
- FR-17650 - Fix auto capitalize email input in login page
=> Update Frontegg AdminPortal to 7.9.0

packages/react/package.json, yarn.lock
- FR-17760 - Fix empty lastSeen column on expanded user info 
- FR-17762 - Fix tree component using mui&#x2F;x-tree-view
- FR-17517 - Fix login direct action race condition
=> Update Frontegg AdminPortal to 7.10.0

packages/react/package.json, yarn.lock
- FR-18217 - Fix impersonation on embedded
- FR-18167 - Fix back to login on magic link
- FR-8030 - fix website dialog cancel button typeography
- FR-17822 - Fix Vanilla JS
- FR-17770 - Fix valtio reset state bug
=> Update Frontegg AdminPortal to 7.13.0

packages/react/package.json, yarn.lock
=> Update Frontegg AdminPortal to 7.16.0

packages/react/package.json, yarn.lock
- FR-18529 - Fixed empty roles field bug when appName is provided
- FR-18353 - Fixed tooltips mount component
=> Update Frontegg AdminPortal to 7.26.0

packages/react/package.json, yarn.lock
- FR-18561 - Fixed get ip metadata when app name is provided
- FR-17091 - Fixed long name in groups and roles
=> Update Frontegg AdminPortal to 7.27.0

packages/react/package.json, yarn.lock
- FR-18341 - Fixed social login button size
- FR-12722 - Fixed Incorrect order of social logins display
=> Update Frontegg AdminPortal to 7.32.0

packages/react/package.json, yarn.lock
- FR-18838 - Added MFA with email code
- FR-17593 - Fixed SAML enable with non SSO user try to login not throwing an error
=> Update Frontegg AdminPortal to 7.34.0

packages/react/package.json, yarn.lock
- FR-18925 - Fixed wrong ip presented in Audit logs table IP column
- FR-18682 - Changed country flags image
=> Update Frontegg AdminPortal to 7.36.0

packages/react/package.json, yarn.lock
- FR-18954 - Fixed MFA with email active state, step and missing erros
- FR-18973 - Added login to show error page only for 5xx errors
=> Update Frontegg AdminPortal to 7.38.0

packages/react/package.json, yarn.lock
- FR-18941 - Fixed permissions evaluation without permissions in JWT
- FR-18966 - Added override error message infrastructure
- FR-18896 - Added RTL support
=> Update Frontegg AdminPortal to 7.40.0

packages/react/package.json, yarn.lock
- FR-18683 - Changed phone number selector input
=> Update Frontegg AdminPortal to 7.41.0

packages/react/package.json, yarn.lock
- FR-19047 - Fixed permissions evalutaion when have more than one permission
- FR-18988 - Fixed missing email on MFA verification description
- FR-19068 - Fixed MFA error appears after clicking on verify another way
- FR-18917 - Fixed user roles deletion
=> Update Frontegg AdminPortal to 7.42.0

packages/react/package.json, yarn.lock
- FR-19079 - Added Suggest Save password in mobile sdk
=> Update Frontegg AdminPortal to 7.43.0

packages/react/package.json, yarn.lock
- FR-19191 - Fixed infinite loop on get ip metadata
=> Update Frontegg AdminPortal to 7.44.0

packages/react/package.json, yarn.lock
- FR-19220 - Fixed roles selection for MSP users
- FR-19205 - Added filter country code by country calling code
- FR-18963 - Added SMS enhancements
=> Update Frontegg AdminPortal to 7.45.0

packages/react/package.json, yarn.lock
- FR-19272 - Fixed sso input
- FR-19068 - Fixed MFA error appears after reset
=> Update Frontegg AdminPortal to 7.48.0

packages/react/package.json, yarn.lock
- FR-19236 - Fixed error handling on OIDC failure
- FR-19301 - Fixed settings list item title
- FR-19121 - Fixed security center recommendations after policy changed
=> Update Frontegg AdminPortal to 7.49.0

packages/react/package.json, yarn.lock
- FR-19387 - Fixed login with apple in iOS devices
- FR-18450 - Changed permissions tree components
=> Update Frontegg AdminPortal to 7.50.0

packages/react/package.json, yarn.lock
- FR-19351 - Fixed MFA with SMS error and inital state bugs
- FR-19269 - Changed initial requests to run in parallel
=> Update Frontegg AdminPortal to 7.51.0

packages/react/package.json, yarn.lock
- FR-19573 - Fixed redundant required asterisk on optional field
- FR-19566 - Fixed navbar route title appearing without items
- FR-19351 - Fixed SMS input calling code replace
=> Update Frontegg AdminPortal to 7.52.0

packages/react/package.json, yarn.lock
- FR-19618 - Fixed FRONTEGG_AFTER_AUTH_REDIRECT_URL usage on custom login
- FR-19509 - Fixed sms as main auth strategy validation
=> Update Frontegg AdminPortal to 7.53.0

packages/react/package.json, yarn.lock
- FR-19037 - Added an option to skip user load
=> Update Frontegg AdminPortal to 7.58.0

packages/react/package.json, yarn.lock
- FR-19037 - Added fallback for skip user load
- FR-19648 - Added password expiration to login box
=> Update Frontegg AdminPortal to 7.59.0

packages/react/package.json, yarn.lock
- FR-19752 - Fixed error not shown in custom role creation
- FR-18568 - Added password rotation support
=> Update Frontegg AdminPortal to 7.60.0

packages/react/package.json, yarn.lock
- FR-19452 - Added a &quot;silent refresh&quot; to switchTenant
=> Update Frontegg AdminPortal to 7.61.0

packages/react/package.json, yarn.lock
- FR-13869 - Fixed autocomplete overrides input theme
- FR-19956 - Fixed missing email for unenreolled MFA users
- FR-20037 - Fixed input focus on user invite dialog
=> Update Frontegg AdminPortal to 7.62.0

packages/react/package.json, yarn.lock
- FR-20068 - Added password config custom tests
=> Update Frontegg AdminPortal to 7.64.0

packages/react/package.json, yarn.lock
- FR-19299 - Fixed Hebrew translation of password rotation
- FR-17951 - Changed the api routes of  profile page&#39;s phone number
=> Update Frontegg AdminPortal to 7.65.0

packages/react/package.json, yarn.lock
- FR-20482 - Added one of validation method to yup boolean interface
- FR-19402 - Fixed UI delete all checkbox
- FR-20398 - Added delete all option to SCIM deletion
- FR-20047 - Added Custom Signup Fields
=> Update Frontegg AdminPortal to 7.68.0

packages/react/package.json, yarn.lock
- FR-20047 - Added support for overrideSignupFields as string js code
- FR-19797 - Fixed bug duplicate request on double click
- FR-20479 - Added type error validation method to yup interfaces
=> Update Frontegg AdminPortal to 7.69.0

packages/react/package.json, yarn.lock
- FR-20337 - Fixed errors not displayed on submit
=> Update Frontegg AdminPortal to 7.72.0

packages/react/package.json, yarn.lock
- FR-20899 - Changed logout user session button
- FR-20901 - Fixed select actions menu item
- FR-20871 - Added support for default language
- FR-20894 - Added support regex in string input
- FR-19718 - Added username strategies
=> Update Frontegg AdminPortal to 7.74.0

packages/react/package.json, yarn.lock
- FR-21242 - Added customization for select phone number country codes
=> Update Frontegg AdminPortal to 7.79.0

packages/react/package.json, yarn.lock
- FR-21360 - Fixed CMCComponents React19 compatibility 
- FR-20601 - Fixed metadata sync when using custom signup fields
- FR-20601 - Fixed custom signup fields visiblity
- FR-21194 - Fixed translations options to have all supported languages
=> Update Frontegg AdminPortal to 7.80.0

packages/react/package.json, yarn.lock
- FR-22006 - Added signup to login direct action
- FR-21912 - Added InvitationLink component (basic version)
- FR-21911 - Added InviteUserViaLink component (basic version)
- FR-21910 - Added an InviteUserSelector component
- FR-21909 - Changed InviteUserForm component to separate file from InviteUserDialog
=> Update Frontegg AdminPortal to 7.83.0

packages/react/package.json, yarn.lock
- FR-22001 - Added Embedded Social Login in MobileSDK
=> Update Frontegg AdminPortal to 7.86.0

packages/react/package.json, yarn.lock
- FR-22238 - Added a &#39;Back&#39; button when both link and form invitations …
- FR-22167 - Fixed username field to be hidden by default in the invite…
=> Update Frontegg AdminPortal to 7.90.0
