frontegg/frontegg-react

- packages/core/src/api/fetch.ts
The call to `.json()` accesses the response's body stream. At that
point, we cannot call another method to access the body stream because
it has already been consumed. The error message is:
```
'Response': body stream already read
```
The fix is to use `response.text()` and parse it as JSON. Or, we could
check the content-type and call the correct access method.
> fix: Calling `response.text()` after `response.json()` fails

- packages/auth/src/HOCs.tsx
take the full path and substring it by the origin length
fixes #134
> fix(auth): add missing query and hash after login redirect

- packages/auth/src/SocialLogins/SocialLogins.tsx
when all social login providers are empty, the OR should not appear
> fix(auth): [FR-1080] fix social login wrapper

- packages/audits/src/components/AuditsRawTable.tsx
Now the filter icon doesn't show if the filterable value is disabled.
> fix(audits): fix show filter icon if the filterable value is disabled

- packages/auth/src/AuthorizedContent/index.tsx
There are many use cases where we want to render Component even if authorization fails 
(e.g render a disable action button if the user has no permissions etc..).
This commit adds the ability to pass render function to `AuthorizedContent` component which in
turn pass the `isAuthorized` value to the render function. This way the
user can decide how to render the component depends on the value of `isAuthorized`.
> feat(auth): support render prop

- packages/core/src/components/TableCells.tsx
fix
core
display audit created at in local time zone using moment library
https://user-images.githubusercontent.com/78534155/108623748-455ba280-7449-11eb-8aea-900c9a0377cb.mov
> FR-1939: show audits in local timezone

- packages/connectivity/README.md
- packages/connectivity/src/components/ConnectivityPage.tsx
- packages/connectivity/src/styles/connectivity.scss
- packages/connectivity/src/styles/content.scss
The `fitContent` property was removed. 
The scrolling of the container was fixed.
The video with a fixed height of the parent container:
https://user-images.githubusercontent.com/4667761/119617937-fe47c980-be0a-11eb-802f-9d8638342779.mov
The video with a free height of the parent container:
https://user-images.githubusercontent.com/4667761/119618018-161f4d80-be0b-11eb-8fc8-ced6ee3c6dbd.mov
FR-3005
> remove the fitContent property

- packages/core/package.json
- packages/react/package.json
- yarn.lock
- FR-3140 - Fix 'replace' module if exists
- FR-3140 - Remove package json module key for Frontegg libraries
- FR-2475 - add custom login footer
- hide subscription tab
> Update Frontegg AdminPortal to 3.10.0

- cypress/helpers.tsx
- packages/core/package.json
- packages/react/package.json
- yarn.lock
- v3.11.0
- FR-3140 - Add trigger vue pipeline on AdminPortal release
- FR-3649 - make sure to load navigation bar only after loading the relevant policy
- FR-3804 - remove last triggered column from webhooks table
- FR-3722 - Subscription Cancel
-  Conflicts:
- store/package.json
- store/src/subscriptions/Billing/Information/saga.ts
- 	yarn.lock
- FR-3643 - Login flow oidc
- FR-3794 - custom link in login
- FR-3806 - update content for webhooks page
- FR-3814 - oidc configuration fixes
- 	packages/ui/src/pages/SubscriptionPage/Checkout/Stripe/StripeSubscriptionCheckoutForm.tsx
- 	packages/ui/src/pages/SubscriptionPage/SubscriptionPage.tsx
> Update Frontegg AdminPortal to 3.11.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- v3.12.0
- FR-3599 - FR-3600 - Dynmic html component
- FR-3848 - Add option to save query param after auth redirect
> Update Frontegg AdminPortal to 3.12.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- v3.13.0
- Fix admin box loading
- FR-3651 Connectivity is sending ~300 fetch requests for slack configuration
- FR-3846 - custom input error
- FR-3863 - cannot add public key manually
- FR-3548 - add externally managed screen, refactor code
> Update Frontegg AdminPortal to 3.13.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- v3.14.1
- FR-3944 - Added custom loader as an option to refetch request authorize
- FR-3981 - when choose other  saml vendor then reset saml config to manual
- id for admin box x
- FR-3889 - support permissions in admin box
- FR-3793 - add login box customizion
- FR-3596 - custom social login icon
> Update Frontegg AdminPortal to 3.14.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- v3.15.0
- FR-3814 - fix configuration
- FR-3944 - remove logs and added custom loader to a condition in injector
- FR-3987 - fix social layout
> Update Frontegg AdminPortal to 3.15.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- v3.16.0
- FR-3543 - Integrate white label mode
- FR-3858 - Support Inner Theme Provider to override theming in every possible level
- FR-3863 - manual saml remove b64
- ids for saml
- FR-4007 - FronteggApiError out of fetch
- Remove unecessary logs
- FR-3649 - Make sure navigation is loading only when policy had been fetched
- FR-3895 - billing info support
- Custom Loader bug - revert unnecessary condition
> Update Frontegg AdminPortal to 3.16.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- 
- [FR-3893](https://frontegg.atlassian.net/browse/FR-3893) - Finalize Embedded bundle - [aa70a8a2](https://github.com/frontegg/admin-box/pulls?q=aa70a8a2)
- [FR-3965](https://frontegg.atlassian.net/browse/FR-3965) - Fix ReCaptcha infinite render - [28702caa](https://github.com/frontegg/admin-box/pulls?q=28702caa)
> Update Frontegg AdminPortal to 4.5.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4163](https://frontegg.atlassian.net/browse/FR-4163) - Cypress unit test - [4c39bd37](https://github.com/frontegg/admin-box/pulls?q=4c39bd37)
> Update Frontegg AdminPortal to 4.8.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4166](https://frontegg.atlassian.net/browse/FR-4166) - remove unused packages - [8681166a](https://github.com/frontegg/admin-box/pulls?q=8681166a)
- [FR-3926](https://frontegg.atlassian.net/browse/FR-3926) - Fix routing bug - [ccb464dd](https://github.com/frontegg/admin-box/pulls?q=ccb464dd)
> Update Frontegg AdminPortal to 4.9.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4154](https://frontegg.atlassian.net/browse/FR-4154) - support invitation token on signup - [ce6f59ed](https://github.com/frontegg/admin-box/pulls?q=ce6f59ed)
- [FR-4151](https://frontegg.atlassian.net/browse/FR-4151) - otc flow - [8ac73190](https://github.com/frontegg/admin-box/pulls?q=8ac73190)
- [FR-3926](https://frontegg.atlassian.net/browse/FR-3926) - Create new saga middleware foreach store - [de4f5b28](https://github.com/frontegg/admin-box/pulls?q=de4f5b28)
> Update Frontegg AdminPortal to 4.10.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-3926](https://frontegg.atlassian.net/browse/FR-3926) - Disable context in Preview Mode - [308bb51e](https://github.com/frontegg/admin-box/pulls?q=308bb51e)
> Update Frontegg AdminPortal to 4.11.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-3926](https://frontegg.atlassian.net/browse/FR-3926) - rename data-testid to data-test-id - [0fca4341](https://github.com/frontegg/admin-box/pulls?q=0fca4341)
- [FR-3965](https://frontegg.atlassian.net/browse/FR-3965) - magic link prelogin page header - [5d2a499f](https://github.com/frontegg/admin-box/pulls?q=5d2a499f)
> Update Frontegg AdminPortal to 4.12.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-3664](https://frontegg.atlassian.net/browse/FR-3664) - Hide vendor children if frontegg routes - [0fff9125](https://github.com/frontegg/admin-box/pulls?q=0fff9125)
> Update Frontegg AdminPortal to 4.13.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-3664](https://frontegg.atlassian.net/browse/FR-3664) - Add signup success url to hideChildren whitelist - [28370a8e](https://github.com/frontegg/admin-box/pulls?q=28370a8e)
> Update Frontegg AdminPortal to 4.15.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4179](https://frontegg.atlassian.net/browse/FR-4179) - fix passwordless postlogin saga loading state - [0a9619fd](https://github.com/frontegg/admin-box/pulls?q=0a9619fd)
> Update Frontegg AdminPortal to 4.16.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4188](https://frontegg.atlassian.net/browse/FR-4188) - add optional to theme options properties - [bb50b7ec](https://github.com/frontegg/admin-box/pulls?q=bb50b7ec)
> Update Frontegg AdminPortal to 4.16.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4187](https://frontegg.atlassian.net/browse/FR-4187) - add payment method update, some refactor - [d3f1e699](https://github.com/frontegg/admin-box/pulls?q=d3f1e699)
- [FR-4220](https://frontegg.atlassian.net/browse/FR-4220) - Login box bugs fixes - [8951df17](https://github.com/frontegg/admin-box/pulls?q=8951df17)
- [FR-4201](https://frontegg.atlassian.net/browse/FR-4201) - inner provider work with relative key - [f43da38b](https://github.com/frontegg/admin-box/pulls?q=f43da38b)
- [FR-3906](https://frontegg.atlassian.net/browse/FR-3906) - Subscription Split Checkout component - [00b8a434](https://github.com/frontegg/admin-box/pulls?q=00b8a434)
- [FR-4192](https://frontegg.atlassian.net/browse/FR-4192) - revert  magic link text - …
> Update Frontegg AdminPortal to 4.17.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4257](https://frontegg.atlassian.net/browse/FR-4257) - fetch request authorize if custom login box or preview mode - [28d3530b](https://github.com/frontegg/admin-box/pulls?q=28d3530b)
- [FR-4021](https://frontegg.atlassian.net/browse/FR-4021) - change secret key input to password input to hide data - [012118ce](https://github.com/frontegg/admin-box/pulls?q=012118ce)
- [FR-4220](https://frontegg.atlassian.net/browse/FR-4220) - support social login success for activation flow - [8ce8325b](https://github.com/frontegg/admin-box/pulls?q=8ce8325b)
- [FR-3905](https://frontegg.atlassian.net/browse/FR-3905) - Skeleton component extraction, profile loading guard - [7e736217](https://github.com/frontegg/admin-box/pulls?q=7e736217)
- [FR-4214](https://frontegg.atlassian.net/browse/FR-4214) - …
> Update Frontegg AdminPortal to 4.18.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4203](https://frontegg.atlassian.net/browse/FR-4203) - support redirect after signup with social login - [ce66565e](https://github.com/frontegg/admin-box/pulls?q=ce66565e)
- [FR-4216](https://frontegg.atlassian.net/browse/FR-4216) - Verify tenant invite - [709f0c4d](https://github.com/frontegg/admin-box/pulls?q=709f0c4d)
- [FR-4280](https://frontegg.atlassian.net/browse/FR-4280) - Subscription style stripe inputs through slot hotfix - [8f8bd486](https://github.com/frontegg/admin-box/pulls?q=8f8bd486)
- [FR-4271](https://frontegg.atlassian.net/browse/FR-4271) - sso activation - [fa4b223f](https://github.com/frontegg/admin-box/pulls?q=fa4b223f)
- [FR-4128](https://frontegg.atlassian.net/browse/FR-4128) - add the a action and a function for retry a we… - …
> Update Frontegg AdminPortal to 4.19.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4274](https://frontegg.atlassian.net/browse/FR-4274) - add no local logins strategy - [1a14bd1b](https://github.com/frontegg/admin-box/pulls?q=1a14bd1b)
- [FR-4326](https://frontegg.atlassian.net/browse/FR-4326) - disable refresh token if hosted login - [d452149e](https://github.com/frontegg/admin-box/pulls?q=d452149e)
- [FR-4234](https://frontegg.atlassian.net/browse/FR-4234) - fix alert message design - [1aec3166](https://github.com/frontegg/admin-box/pulls?q=1aec3166)
- [FR-3678](https://frontegg.atlassian.net/browse/FR-3678) - add mock data for subscriptions demo mode - [4512dc3f](https://github.com/frontegg/admin-box/pulls?q=4512dc3f)
> Update Frontegg AdminPortal to 4.21.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4238](https://frontegg.atlassian.net/browse/FR-4238) - support customization of width of login box and alignment to support split mode - [b0cb8ce9](https://github.com/frontegg/admin-box/pulls?q=b0cb8ce9)
- [FR-4290](https://frontegg.atlassian.net/browse/FR-4290) - disable edit option on loading checkout. - [a8243ea9](https://github.com/frontegg/admin-box/pulls?q=a8243ea9)
- [FR-4307](https://frontegg.atlassian.net/browse/FR-4307) - user allowed to update any field in billing details - [6e94d94a](https://github.com/frontegg/admin-box/pulls?q=6e94d94a)
- [FR-4295](https://frontegg.atlassian.net/browse/FR-4295) - hide billing component if no payment method - [eee0a02a](https://github.com/frontegg/admin-box/pulls?q=eee0a02a)
> Update Frontegg AdminPortal to 4.21.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4339](https://frontegg.atlassian.net/browse/FR-4339) - fix dynamic component - [bd1e5d54](https://github.com/frontegg/admin-box/pulls?q=bd1e5d54)
- [FR-4297](https://frontegg.atlassian.net/browse/FR-4297) - Subscription permissions - [40f635da](https://github.com/frontegg/admin-box/pulls?q=40f635da)
- [FR-3677](https://frontegg.atlassian.net/browse/FR-3677) - add activate account link expired component to login box - [6018b8b9](https://github.com/frontegg/admin-box/pulls?q=6018b8b9)
- [FR-4331](https://frontegg.atlassian.net/browse/FR-4331) - remove company name - [c75e8151](https://github.com/frontegg/admin-box/pulls?q=c75e8151)
> Update Frontegg AdminPortal to 4.21.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4296](https://frontegg.atlassian.net/browse/FR-4296) - enter submit - [17a4ac26](https://github.com/frontegg/admin-box/pulls?q=17a4ac26)
- [FR-4074](https://frontegg.atlassian.net/browse/FR-4074) - build inline dynamic imports to support vitejs build - [e43991a6](https://github.com/frontegg/admin-box/pulls?q=e43991a6)
> Update Frontegg AdminPortal to 4.22.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4618](https://frontegg.atlassian.net/browse/FR-4618) - added localization for MFA disable dialog validation - [cd67e494](https://github.com/frontegg/admin-box/pulls?q=cd67e494)
- [FR-4623](https://frontegg.atlassian.net/browse/FR-4623) - update rest api version - [b3b2485e](https://github.com/frontegg/admin-box/pulls?q=b3b2485e)
> Update Frontegg AdminPortal to 4.37.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4552](https://frontegg.atlassian.net/browse/FR-4552) - users page sub tenants - [b64fc8d6](https://github.com/frontegg/admin-box/pulls?q=b64fc8d6)
- [FR-4365](https://frontegg.atlassian.net/browse/FR-4365) - change day(s) to day, days - [50fccb78](https://github.com/frontegg/admin-box/pulls?q=50fccb78)
- [FR-4685](https://frontegg.atlassian.net/browse/FR-4685) - Subscriptions hidden stripe form - [9e05600b](https://github.com/frontegg/admin-box/pulls?q=9e05600b)
> Update Frontegg AdminPortal to 4.39.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4741](https://frontegg.atlassian.net/browse/FR-4741) - Browser Autofill Credentials in LoginBox - [5c8308e7](https://github.com/frontegg/admin-box/pulls?q=5c8308e7)
> Update Frontegg AdminPortal to 4.39.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4779](https://frontegg.atlassian.net/browse/FR-4779) - adding missing data test ids and hide the input hidden ref … - [1fd055bf](https://github.com/frontegg/admin-box/pulls?q=1fd055bf)
> Update Frontegg AdminPortal to 4.39.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4850](https://frontegg.atlassian.net/browse/FR-4850) - remove unused styles - [6ccb99bc](https://github.com/frontegg/admin-box/pulls?q=6ccb99bc)
- [FR-4786](https://frontegg.atlassian.net/browse/FR-4786) - addded another hook on the react-hooks and type - [f3e7e9b7](https://github.com/frontegg/admin-box/pulls?q=f3e7e9b7)
- [FR-4717](https://frontegg.atlassian.net/browse/FR-4717) - fix login error - [94408a24](https://github.com/frontegg/admin-box/pulls?q=94408a24)
- [FR-4786](https://frontegg.atlassian.net/browse/FR-4786) - supporting hosted login on login-box - [70523fdc](https://github.com/frontegg/admin-box/pulls?q=70523fdc)
> Update Frontegg AdminPortal to 4.42.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5043](https://frontegg.atlassian.net/browse/FR-5043) - fix social login does not redirect on success when adding… - [526bcc43](https://github.com/frontegg/admin-box/pulls?q=526bcc43)
- [FR-2810](https://frontegg.atlassian.net/browse/FR-2810) - fix users can't recover their mfa after social login - [55306297](https://github.com/frontegg/admin-box/pulls?q=55306297)
- [FR-4943](https://frontegg.atlassian.net/browse/FR-4943) - add support for chrome/safari/firefox auto completion for login inputs - [eb37930a](https://github.com/frontegg/admin-box/pulls?q=eb37930a)
- [FR-4842](https://frontegg.atlassian.net/browse/FR-4842) - Fix validation error messages - [ef3a0da7](https://github.com/frontegg/admin-box/pulls?q=ef3a0da7)
> Update Frontegg AdminPortal to 4.43.0

- lerna.json
- packages/audits/package.json
- packages/auth/package.json
- packages/auth/src/tests/forget-password-flow.cy-spec.tsx
- packages/auth/src/tests/login-flow.cy-spec.tsx
- packages/cli/package.json
- packages/connectivity/package.json
- packages/core/package.json
- packages/demo-saas/package.json
- packages/elements-material-ui/package.json
- packages/elements-semantic/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-4415](https://frontegg.atlassian.net/browse/FR-4415) - Adjust Theme for onboarding builder - [c6270091](https://github.com/frontegg/admin-box/pulls?q=c6270091)
- [FR-5104](https://frontegg.atlassian.net/browse/FR-5104) - change default navigation metadata - [d1d0170e](https://github.com/frontegg/admin-box/pulls?q=d1d0170e)
- [FR-4517](https://frontegg.atlassian.net/browse/FR-4517) - new sso page - [1733992b](https://github.com/frontegg/admin-box/pulls?q=1733992b)
> Update Frontegg AdminPortal to 5.3.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5163](https://frontegg.atlassian.net/browse/FR-5163) - support Social login dev credentials - [7cc6d76b](https://github.com/frontegg/admin-box/pulls?q=7cc6d76b)
> Update Frontegg AdminPortal to 5.6.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5159](https://frontegg.atlassian.net/browse/FR-5159) - fix sso model hight and steps title - [40c22cb0](https://github.com/frontegg/admin-box/pulls?q=40c22cb0)
- [FR-5282](https://frontegg.atlassian.net/browse/FR-5282) - nextjs uuid compile fix - [3db3b3ee](https://github.com/frontegg/admin-box/pulls?q=3db3b3ee)
- [FR-5106](https://frontegg.atlassian.net/browse/FR-5106) - add ability to handle refresh long refresh token - [ed1c629f](https://github.com/frontegg/admin-box/pulls?q=ed1c629f)
- [FR-4289](https://frontegg.atlassian.net/browse/FR-4289) - fix error state in login box - [e18936f4](https://github.com/frontegg/admin-box/pulls?q=e18936f4)
> Update Frontegg AdminPortal to 5.9.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5109](https://frontegg.atlassian.net/browse/FR-5109) - render social logins as icons only if more than 3 buttons - [52552828](https://github.com/frontegg/admin-box/pulls?q=52552828)
> Update Frontegg AdminPortal to 5.9.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5339](https://frontegg.atlassian.net/browse/FR-5339) - added content max height prop to table - [b73d6b49](https://github.com/frontegg/admin-box/pulls?q=b73d6b49)
- [FR-5339](https://frontegg.atlassian.net/browse/FR-5339) - invoice table height - [275c7f75](https://github.com/frontegg/admin-box/pulls?q=275c7f75)
- [FR-5335](https://frontegg.atlassian.net/browse/FR-5335) - fixed MFA recovery design - [ec74d474](https://github.com/frontegg/admin-box/pulls?q=ec74d474)
- [FR-5329](https://frontegg.atlassian.net/browse/FR-5329) - send invite link on failed sso - [d75bcb2a](https://github.com/frontegg/admin-box/pulls?q=d75bcb2a)
- [FR-5295](https://frontegg.atlassian.net/browse/FR-5295) - Reformat Subscriptions Page - [0f347ecf](https://github.com/frontegg/admin-box/pulls?q=0f347ecf)
> Update Frontegg AdminPortal to 5.10.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5547](https://frontegg.atlassian.net/browse/FR-5547) - fix captcha visibility - [e6e2906e](https://github.com/frontegg/admin-box/pulls?q=e6e2906e)
- [FR-5127](https://frontegg.atlassian.net/browse/FR-5127) - add condition style in activate account for dark mode - [1426b80c](https://github.com/frontegg/admin-box/pulls?q=1426b80c)
- [FR-4687](https://frontegg.atlassian.net/browse/FR-4687) - wrap authenticator link text with spaces - [0dcb8feb](https://github.com/frontegg/admin-box/pulls?q=0dcb8feb)
> Update Frontegg AdminPortal to 5.14.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5598](https://frontegg.atlassian.net/browse/FR-5598) - test reset password flow - [0ca85943](https://github.com/frontegg/admin-box/pulls?q=0ca85943)
- [FR-5597](https://frontegg.atlassian.net/browse/FR-5597) - Test forgot password flow - [42c473a2](https://github.com/frontegg/admin-box/pulls?q=42c473a2)
- [FR-5524](https://frontegg.atlassian.net/browse/FR-5524) - test account details add and edit flow - [20460253](https://github.com/frontegg/admin-box/pulls?q=20460253)
> Update Frontegg AdminPortal to 5.14.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5617](https://frontegg.atlassian.net/browse/FR-5617) - add auto foucs to mfa - [5fa73d32](https://github.com/frontegg/admin-box/pulls?q=5fa73d32)
- [FR-5558](https://frontegg.atlassian.net/browse/FR-5558) - saml callback - [e1d8b400](https://github.com/frontegg/admin-box/pulls?q=e1d8b400)
- [FR-5602](https://frontegg.atlassian.net/browse/FR-5602) - trim trailing slash from base url passed to options - [01027f4e](https://github.com/frontegg/admin-box/pulls?q=01027f4e)
> Update Frontegg AdminPortal to 5.15.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5714](https://frontegg.atlassian.net/browse/FR-5714) - use urlPrefix when loading metadata - [9438151f](https://github.com/frontegg/admin-box/pulls?q=9438151f)
- [FR-5712](https://frontegg.atlassian.net/browse/FR-5712) - remove logs from code - [a30f83cd](https://github.com/frontegg/admin-box/pulls?q=a30f83cd)
- [FR-5652](https://frontegg.atlassian.net/browse/FR-5652) - create login message copmonent - [84e5a01d](https://github.com/frontegg/admin-box/pulls?q=84e5a01d)
- [FR-5477](https://frontegg.atlassian.net/browse/FR-5477) - Personal tokens tests - [5f4e18ba](https://github.com/frontegg/admin-box/pulls?q=5f4e18ba)
> Update Frontegg AdminPortal to 5.16.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5341](https://frontegg.atlassian.net/browse/FR-5341) - remove inactive provider from button count - [d11f3972](https://github.com/frontegg/admin-box/pulls?q=d11f3972)
> Update Frontegg AdminPortal to 5.16.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5610](https://frontegg.atlassian.net/browse/FR-5610) - align login messages - [801f6ae8](https://github.com/frontegg/admin-box/pulls?q=801f6ae8)
- [FR-5827](https://frontegg.atlassian.net/browse/FR-5827) - fix error on redirect - [059e4617](https://github.com/frontegg/admin-box/pulls?q=059e4617)
- [FR-5650](https://frontegg.atlassian.net/browse/FR-5650) - refrain from rendering different button component on loading - [3696a553](https://github.com/frontegg/admin-box/pulls?q=3696a553)
- [FR-5234](https://frontegg.atlassian.net/browse/FR-5234) - replace page loader wherever a wrapping box is rendered - [638233e7](https://github.com/frontegg/admin-box/pulls?q=638233e7)
- [FR-5654](https://frontegg.atlassian.net/browse/FR-5654) - fix invite to tenant link permission - …
> Update Frontegg AdminPortal to 5.16.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5853](https://frontegg.atlassian.net/browse/FR-5853) - fix import - [7da695e1](https://github.com/frontegg/admin-box/pulls?q=7da695e1)
- [FR-5853](https://frontegg.atlassian.net/browse/FR-5853) - fix disign for back to login button - [b8af1934](https://github.com/frontegg/admin-box/pulls?q=b8af1934)
> Update Frontegg AdminPortal to 5.16.3

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5857](https://frontegg.atlassian.net/browse/FR-5857) - SAML + social logins + OIDC failure screen doesn't show the… - [01c4e053](https://github.com/frontegg/admin-box/pulls?q=01c4e053)
> Update Frontegg AdminPortal to 5.16.4

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5885](https://frontegg.atlassian.net/browse/FR-5885) - revert loaders change - [92feb1bc](https://github.com/frontegg/admin-box/pulls?q=92feb1bc)
> Update Frontegg AdminPortal to 5.16.5

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5904](https://frontegg.atlassian.net/browse/FR-5904) - User should be able to customize admin portal background color - [21a34f2f](https://github.com/frontegg/admin-box/pulls?q=21a34f2f)
> Update Frontegg AdminPortal to 5.17.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6001](https://frontegg.atlassian.net/browse/FR-6001) - clean @frontegg/types from React nodes - [b330190c](https://github.com/frontegg/admin-box/pulls?q=b330190c)
- [FR-5607](https://frontegg.atlassian.net/browse/FR-5607) - Add support for hooks in custom components - [206b1654](https://github.com/frontegg/admin-box/pulls?q=206b1654)
> Update Frontegg AdminPortal to 5.18.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5781](https://frontegg.atlassian.net/browse/FR-5781) - make sure activation form is not blink when not needed - [87142238](https://github.com/frontegg/admin-box/pulls?q=87142238)
> Update Frontegg AdminPortal to 5.18.3

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6338](https://frontegg.atlassian.net/browse/FR-6338) - Add managed subscriptions state - [22a52494](https://github.com/frontegg/admin-box/pulls?q=22a52494)
- [FR-6069](https://frontegg.atlassian.net/browse/FR-6069) - reset phone number flow - [97366f99](https://github.com/frontegg/admin-box/pulls?q=97366f99)
- [FR-6069](https://frontegg.atlassian.net/browse/FR-6069) - sms otc passwordless sign up - [0db8d844](https://github.com/frontegg/admin-box/pulls?q=0db8d844)
- [FR-5588](https://frontegg.atlassian.net/browse/FR-5588) - New account/user sign up flows - [c7cf0f2c](https://github.com/frontegg/admin-box/pulls?q=c7cf0f2c)
> Update Frontegg AdminPortal to 5.22.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6338](https://frontegg.atlassian.net/browse/FR-6338) - Add missing props managed subscription - [dc76fe97](https://github.com/frontegg/admin-box/pulls?q=dc76fe97)
> Update Frontegg AdminPortal to 5.23.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6394](https://frontegg.atlassian.net/browse/FR-6394) - added tracing support to FronteggOptions - [7b0dd9c2](https://github.com/frontegg/admin-box/pulls?q=7b0dd9c2)
- [FR-6314](https://frontegg.atlassian.net/browse/FR-6314) - single plan checkout - [3fbd7d73](https://github.com/frontegg/admin-box/pulls?q=3fbd7d73)
- [FR-6314](https://frontegg.atlassian.net/browse/FR-6314) - Managed Subscription usage - [4d25f1e4](https://github.com/frontegg/admin-box/pulls?q=4d25f1e4)
- [FR-6338](https://frontegg.atlassian.net/browse/FR-6338) - Return a single subscription - [57dda72e](https://github.com/frontegg/admin-box/pulls?q=57dda72e)
- [FR-6385](https://frontegg.atlassian.net/browse/FR-6385) - Skipped a test failing for a known issue with React query params and fix type of reset phone number …
> Update Frontegg AdminPortal to 5.27.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6395](https://frontegg.atlassian.net/browse/FR-6395) - added sentry support - [b8d41145](https://github.com/frontegg/admin-box/pulls?q=b8d41145)
- [FR-6363](https://frontegg.atlassian.net/browse/FR-6363) - remove frontegg update billing - [80856ebf](https://github.com/frontegg/admin-box/pulls?q=80856ebf)
- [FR-6363](https://frontegg.atlassian.net/browse/FR-6363) - dialog closing issue - [cd755672](https://github.com/frontegg/admin-box/pulls?q=cd755672)
> Update Frontegg AdminPortal to 5.28.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6407](https://frontegg.atlassian.net/browse/FR-6407) - Trial Flow - [205d019b](https://github.com/frontegg/admin-box/pulls?q=205d019b)
- [FR-6395](https://frontegg.atlassian.net/browse/FR-6395) - added console tracing to sentry support - [fa24e46c](https://github.com/frontegg/admin-box/pulls?q=fa24e46c)
> Update Frontegg AdminPortal to 5.29.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/nextjs/src/FronteggProvider.tsx
- packages/react/package.json
- yarn.lock
- [FR-6373](https://frontegg.atlassian.net/browse/FR-6373) - subscription beta logic additions - [51539192](https://github.com/frontegg/admin-box/pulls?q=51539192)
- [FR-6311](https://frontegg.atlassian.net/browse/FR-6311) - export app holder for cjs build - [63f49250](https://github.com/frontegg/admin-box/pulls?q=63f49250)
- [FR-6373](https://frontegg.atlassian.net/browse/FR-6373) - subscription beta types and hooks - [0085f554](https://github.com/frontegg/admin-box/pulls?q=0085f554)
- [FR-6591](https://frontegg.atlassian.net/browse/FR-6591) - subscriptions trialing chip not going away - [954e0bdc](https://github.com/frontegg/admin-box/pulls?q=954e0bdc)
- [FR-6539](https://frontegg.atlassian.net/browse/FR-6539) - Fix update billing details - …
> Update Frontegg AdminPortal to 5.31.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6769](https://frontegg.atlassian.net/browse/FR-6769) - Subscription trial loading - [1767ebd8](https://github.com/frontegg/admin-box/pulls?q=1767ebd8)
- [FR-6727](https://frontegg.atlassian.net/browse/FR-6727) - externally managed hidden components - [e3a2887b](https://github.com/frontegg/admin-box/pulls?q=e3a2887b)
> Update Frontegg AdminPortal to 5.32.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6887](https://frontegg.atlassian.net/browse/FR-6887) - fix timezome for tests - [74092232](https://github.com/frontegg/admin-box/pulls?q=74092232)
- [FR-6886](https://frontegg.atlassian.net/browse/FR-6886) - move code challenge from sessionStorage to localStorage - [a4a27344](https://github.com/frontegg/admin-box/pulls?q=a4a27344)
- [FR-6797](https://frontegg.atlassian.net/browse/FR-6797) - update plan isSIngular disabled - [a8d0be03](https://github.com/frontegg/admin-box/pulls?q=a8d0be03)
- [FR-6797](https://frontegg.atlassian.net/browse/FR-6797) - Subscription - No cancellation for trialing/free plan/default plan - [281aa6cc](https://github.com/frontegg/admin-box/pulls?q=281aa6cc)
- [FR-6769](https://frontegg.atlassian.net/browse/FR-6769) - Trial ended state mutation - …
> Update Frontegg AdminPortal to 5.33.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6887](https://frontegg.atlassian.net/browse/FR-6887) - fix timezome for tests - [5a298a36](https://github.com/frontegg/admin-box/pulls?q=5a298a36)
- [FR-6722](https://frontegg.atlassian.net/browse/FR-6722) - Validate Domain Regex fix - [41fd8875](https://github.com/frontegg/admin-box/pulls?q=41fd8875)
> Update Frontegg AdminPortal to 5.33.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6899](https://frontegg.atlassian.net/browse/FR-6899) - Subscriptions - use cancellation and renewal - [26f32adb](https://github.com/frontegg/admin-box/pulls?q=26f32adb)
- [FR-6899](https://frontegg.atlassian.net/browse/FR-6899) - load properly, information state with managed-subscriptions - [9cc6c080](https://github.com/frontegg/admin-box/pulls?q=9cc6c080)
- [FR-6882](https://frontegg.atlassian.net/browse/FR-6882) - subscription action buttons logic - [36f2696f](https://github.com/frontegg/admin-box/pulls?q=36f2696f)
- [FR-6908](https://frontegg.atlassian.net/browse/FR-6908) - fix routes in case of hosted login box - [fa4df58c](https://github.com/frontegg/admin-box/pulls?q=fa4df58c)
> Update Frontegg AdminPortal to 5.34.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7057](https://frontegg.atlassian.net/browse/FR-7057) - Handle cancellation modals and state - [2c6967cc](https://github.com/frontegg/admin-box/pulls?q=2c6967cc)
- [FR-6899](https://frontegg.atlassian.net/browse/FR-6899) - use subscription instead of billing - [a78e79fa](https://github.com/frontegg/admin-box/pulls?q=a78e79fa)
- 
- [FR-6899](https://frontegg.atlassian.net/browse/FR-6899) - fix subsription state - [eb346846](https://github.com/frontegg/admin-box/pulls?q=eb346846)
- [FR-6899](https://frontegg.atlassian.net/browse/FR-6899) - subscription load with billing information and tenantId - [31093cef](https://github.com/frontegg/admin-box/pulls?q=31093cef)
> Update Frontegg AdminPortal to 5.37.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7063](https://frontegg.atlassian.net/browse/FR-7063) - skip unstable test, leave todo comment to fix it - [af81ec79](https://github.com/frontegg/admin-box/pulls?q=af81ec79)
- [FR-7063](https://frontegg.atlassian.net/browse/FR-7063) - create admin box renderer class - [997a12d2](https://github.com/frontegg/admin-box/pulls?q=997a12d2)
> Update Frontegg AdminPortal to 5.38.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-0000](https://frontegg.atlassian.net/browse/FR-0000) - remove payload loadSubscription - [2e08a892](https://github.com/frontegg/admin-box/pulls?q=2e08a892)
- [FR-0000](https://frontegg.atlassian.net/browse/FR-0000) - remove tenantId from subscription load - [dadb144f](https://github.com/frontegg/admin-box/pulls?q=dadb144f)
- [FR-7124](https://frontegg.atlassian.net/browse/FR-7124) - Hide renew text on free plan - [27c3909e](https://github.com/frontegg/admin-box/pulls?q=27c3909e)
> Update Frontegg AdminPortal to 5.39.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7233](https://frontegg.atlassian.net/browse/FR-7233) - Support custom events for user verification and sign up - [c8ef20c1](https://github.com/frontegg/admin-box/pulls?q=c8ef20c1)
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - add support for multiple baseUrl based on url - [ff78ed09](https://github.com/frontegg/admin-box/pulls?q=ff78ed09)
> Update Frontegg AdminPortal to 5.40.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- 
- [FR-7233](https://frontegg.atlassian.net/browse/FR-7233) - fix to custom event - [fee9df50](https://github.com/frontegg/admin-box/pulls?q=fee9df50)
> Update Frontegg AdminPortal to 5.42.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6311](https://frontegg.atlassian.net/browse/FR-6311) - disable focus handler if nextjs ssr - [0bd30afa](https://github.com/frontegg/admin-box/pulls?q=0bd30afa)
> Update Frontegg AdminPortal to 5.42.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7267](https://frontegg.atlassian.net/browse/FR-7267) - fix failed demo-saas test - [b950706d](https://github.com/frontegg/admin-box/pulls?q=b950706d)
- [FR-7267](https://frontegg.atlassian.net/browse/FR-7267) -  remove use memo for routes in AppNavigation - [0afecb6f](https://github.com/frontegg/admin-box/pulls?q=0afecb6f)
> Update Frontegg AdminPortal to 5.43.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7316](https://frontegg.atlassian.net/browse/FR-7316) - dummy commit to run pipeline again to release admin box version successfully - [07c721da](https://github.com/frontegg/admin-box/pulls?q=07c721da)
> Update Frontegg AdminPortal to 5.44.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - Support nextjs ssr - [d68c1b67](https://github.com/frontegg/admin-box/pulls?q=d68c1b67)
- [FR-7306](https://frontegg.atlassian.net/browse/FR-7306) - add hash routing handling - [2d4e6e4c](https://github.com/frontegg/admin-box/pulls?q=2d4e6e4c)
- [FR-7280](https://frontegg.atlassian.net/browse/FR-7280) - builder resolution support - [1d681e3c](https://github.com/frontegg/admin-box/pulls?q=1d681e3c)
> Update Frontegg AdminPortal to 5.45.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7306](https://frontegg.atlassian.net/browse/FR-7306) - dummy pr - [3c627a6c](https://github.com/frontegg/admin-box/pulls?q=3c627a6c)
> Update Frontegg AdminPortal to 5.45.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7306](https://frontegg.atlassian.net/browse/FR-7306) - add RoutesLayoutPreviewMode - [65f5ed80](https://github.com/frontegg/admin-box/pulls?q=65f5ed80)
- [FR-7353](https://frontegg.atlassian.net/browse/FR-7353) - update rest-api version - [11476ed4](https://github.com/frontegg/admin-box/pulls?q=11476ed4)
> Update Frontegg AdminPortal to 5.47.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7372](https://frontegg.atlassian.net/browse/FR-7372) - update phone validation - [33e7f452](https://github.com/frontegg/admin-box/pulls?q=33e7f452)
> Update Frontegg AdminPortal to 5.48.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7381](https://frontegg.atlassian.net/browse/FR-7381) - Builder / admin box modules / webhooks event are not selectable - [b2791c21](https://github.com/frontegg/admin-box/pulls?q=b2791c21)
- [FR-7176](https://frontegg.atlassian.net/browse/FR-7176) - Subscriptions Checkout Dialog Component - [6e2bda48](https://github.com/frontegg/admin-box/pulls?q=6e2bda48)
- [FR-7172](https://frontegg.atlassian.net/browse/FR-7172) - Privacy tests - [b15e7ba0](https://github.com/frontegg/admin-box/pulls?q=b15e7ba0)
> Update Frontegg AdminPortal to 5.49.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-6969](https://frontegg.atlassian.net/browse/FR-6969) - terms and conditions - [79fc940a](https://github.com/frontegg/admin-box/pulls?q=79fc940a)
- [FR-7623](https://frontegg.atlassian.net/browse/FR-7623) - Builder / admin portal preview - workspace subtitle is being showed even if no tabs appear - [390700a2](https://github.com/frontegg/admin-box/pulls?q=390700a2)
- [FR-7171](https://frontegg.atlassian.net/browse/FR-7171) - security tests - [304b9ee7](https://github.com/frontegg/admin-box/pulls?q=304b9ee7)
> Update Frontegg AdminPortal to 5.51.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7623](https://frontegg.atlassian.net/browse/FR-7623) - Builder / admin portal preview - workspace subtitle is being shown even if not tabs appears. - [ec64c0c1](https://github.com/frontegg/admin-box/pulls?q=ec64c0c1)
> Update Frontegg AdminPortal to 5.51.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7623](https://frontegg.atlassian.net/browse/FR-7623) - dummy commit for releasing a version - [f7d68b6e](https://github.com/frontegg/admin-box/pulls?q=f7d68b6e)
> Update Frontegg AdminPortal to 5.51.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - Update rest api version for NextJS routes - [4f877fa9](https://github.com/frontegg/admin-box/pulls?q=4f877fa9)
- [FR-7408](https://frontegg.atlassian.net/browse/FR-7408) - Subscription Trial Ended Text update - [17c1c6fc](https://github.com/frontegg/admin-box/pulls?q=17c1c6fc)
> Update Frontegg AdminPortal to 5.52.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7726](https://frontegg.atlassian.net/browse/FR-7726) - Dummy commit for releasing a version - [969e112d](https://github.com/frontegg/admin-box/pulls?q=969e112d)
> Update Frontegg AdminPortal to 5.53.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7775](https://frontegg.atlassian.net/browse/FR-7775) - fix tests for disclaimer checkbox - [e7f41291](https://github.com/frontegg/admin-box/pulls?q=e7f41291)
- [FR-7782](https://frontegg.atlassian.net/browse/FR-7782) - Update CODEOWNERS - [c01b14fa](https://github.com/frontegg/admin-box/pulls?q=c01b14fa)
- [FR-7775](https://frontegg.atlassian.net/browse/FR-7775) - change default text of disclaimer checkbox label - [e287e94a](https://github.com/frontegg/admin-box/pulls?q=e287e94a)
> Update Frontegg AdminPortal to 5.53.3

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7813](https://frontegg.atlassian.net/browse/FR-7813) - dummy commit for version - [ff562355](https://github.com/frontegg/admin-box/pulls?q=ff562355)
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - render children if hosted login - [690b9b03](https://github.com/frontegg/admin-box/pulls?q=690b9b03)
> Update Frontegg AdminPortal to 5.54.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- 
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - Prevent disable loading if hosted login and NextJS until SSR finished - [c7a34e93](https://github.com/frontegg/admin-box/pulls?q=c7a34e93)
> Update Frontegg AdminPortal to 5.55.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7903](https://frontegg.atlassian.net/browse/FR-7903) - update rest-api version - [3f95786b](https://github.com/frontegg/admin-box/pulls?q=3f95786b)
> Update Frontegg AdminPortal to 5.56.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7910](https://frontegg.atlassian.net/browse/FR-7910) - align mfa options with vendor policy - [0d817085](https://github.com/frontegg/admin-box/pulls?q=0d817085)
- [FR-7898](https://frontegg.atlassian.net/browse/FR-7898) - Showing a proper error if the vendor policy is not found - [2301032b](https://github.com/frontegg/admin-box/pulls?q=2301032b)
> Update Frontegg AdminPortal to 5.57.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7411](https://frontegg.atlassian.net/browse/FR-7411) - add new themes for new layout - [8491882f](https://github.com/frontegg/admin-box/pulls?q=8491882f)
- [FR-7659](https://frontegg.atlassian.net/browse/FR-7659) - Fixes for social login buttons - [b3592c5f](https://github.com/frontegg/admin-box/pulls?q=b3592c5f)
> Update Frontegg AdminPortal to 5.57.2

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7659](https://frontegg.atlassian.net/browse/FR-7659) - dummy commit - [2f382e91](https://github.com/frontegg/admin-box/pulls?q=2f382e91)
> Update Frontegg AdminPortal to 5.57.4

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-5604](https://frontegg.atlassian.net/browse/FR-5604) - show children only hosted login and nextjs - [52d1f0ee](https://github.com/frontegg/admin-box/pulls?q=52d1f0ee)
> Update Frontegg AdminPortal to 5.58.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - login box split improvements - [3db87e14](https://github.com/frontegg/admin-box/pulls?q=3db87e14)
- [FR-7659](https://frontegg.atlassian.net/browse/FR-7659) - Fixes for social login buttons - [bfd27104](https://github.com/frontegg/admin-box/pulls?q=bfd27104)
> Update Frontegg AdminPortal to 5.58.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - only one testimonial render - [747d7e5d](https://github.com/frontegg/admin-box/pulls?q=747d7e5d)
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - remove wrap page from child signup components - [d45abd29](https://github.com/frontegg/admin-box/pulls?q=d45abd29)
> Update Frontegg AdminPortal to 5.59.1

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7822](https://frontegg.atlassian.net/browse/FR-7822) - Make font family change in all places - [a48946af](https://github.com/frontegg/admin-box/pulls?q=a48946af)
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - change divider style for split mode for each template - [36cfbd30](https://github.com/frontegg/admin-box/pulls?q=36cfbd30)
- [FR-7398](https://frontegg.atlassian.net/browse/FR-7398) - added all users page - [b26343e3](https://github.com/frontegg/admin-box/pulls?q=b26343e3)
- [FR-7938](https://frontegg.atlassian.net/browse/FR-7938) - added option to display invite dialog without the email - [4a293f6f](https://github.com/frontegg/admin-box/pulls?q=4a293f6f)
> Update Frontegg AdminPortal to 5.60.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-7938](https://frontegg.atlassian.net/browse/FR-7938) - fixed state - [65c8fdaa](https://github.com/frontegg/admin-box/pulls?q=65c8fdaa)
- [FR-7354](https://frontegg.atlassian.net/browse/FR-7354) - Speedy login feature - [e4dfd2d7](https://github.com/frontegg/admin-box/pulls?q=e4dfd2d7)
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - fix testimonials carousel - [360110ad](https://github.com/frontegg/admin-box/pulls?q=360110ad)
- [FR-7411](https://frontegg.atlassian.net/browse/FR-7411) - webauthn cards - [7546bf12](https://github.com/frontegg/admin-box/pulls?q=7546bf12)
- [FR-7411](https://frontegg.atlassian.net/browse/FR-7411) - webauthn and secondary strategies saga - [1892b40b](https://github.com/frontegg/admin-box/pulls?q=1892b40b)
- …
> Update Frontegg AdminPortal to 5.61.0

- packages/core/package.json
- packages/nextjs/package.json
- packages/react/package.json
- yarn.lock
- [FR-8053](https://frontegg.atlassian.net/browse/FR-8053) - add user email for mfa recover login saga - [7abb77af](https://github.com/frontegg/admin-box/pulls?q=7abb77af)
- [FR-7231](https://frontegg.atlassian.net/browse/FR-7231) - split mode css bug fix - [38769091](https://github.com/frontegg/admin-box/pulls?q=38769091)
> Update Frontegg AdminPortal to 5.62.0

- packages/react/package.json
- yarn.lock
- [FR-8258](https://frontegg.atlassian.net/browse/FR-8258) - skipped webhooks tests to avoid flakyness - [49effd1f](https://github.com/frontegg/admin-box/pulls?q=49effd1f)
- [FR-8246](https://frontegg.atlassian.net/browse/FR-8246) - Fix preview mode bug with all accounts subtitle - [c74073ee](https://github.com/frontegg/admin-box/pulls?q=c74073ee)
> Update Frontegg AdminPortal to 5.66.1

- packages/react/package.json
- yarn.lock
- [FR-8260](https://frontegg.atlassian.net/browse/FR-8260) - add next js repo to the release pipeline to upgrade admin portal version automatically - [e272ce07](https://github.com/frontegg/admin-box/pulls?q=e272ce07)
> Update Frontegg AdminPortal to 5.66.2

- packages/react/package.json
- yarn.lock
- [FR-8264](https://frontegg.atlassian.net/browse/FR-8264) - fix testimonials text align settings - [f8f2ef3d](https://github.com/frontegg/admin-box/pulls?q=f8f2ef3d)
- [FR-8264](https://frontegg.atlassian.net/browse/FR-8264) - fix logos proportions for big images - [d71d82c7](https://github.com/frontegg/admin-box/pulls?q=d71d82c7)
- [FR-8260](https://frontegg.atlassian.net/browse/FR-8260) - change path to be the correct one - [31a41f24](https://github.com/frontegg/admin-box/pulls?q=31a41f24)
> Update Frontegg AdminPortal to 5.67.0

- packages/react/package.json
- yarn.lock
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - Fixing Pipeline by lock a version of del - [13c0ecf0](https://github.com/frontegg/admin-box/pulls?q=13c0ecf0)
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - Fixing Pipeline by lock a version of del - [c47ed247](https://github.com/frontegg/admin-box/pulls?q=c47ed247)
- [FR-8351](https://frontegg.atlassian.net/browse/FR-8351) - fix speedy with some split templates - [25e3f33a](https://github.com/frontegg/admin-box/pulls?q=25e3f33a)
- [FR-7824](https://frontegg.atlassian.net/browse/FR-7824) - split mode bugfix - [f4a61851](https://github.com/frontegg/admin-box/pulls?q=f4a61851)
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - Fixing Pipeline - [9da8ff08](https://github.com/frontegg/admin-box/pulls?q=9da8ff0 …
> Update Frontegg AdminPortal to 5.68.0

- packages/react/package.json
- yarn.lock
- [FR-8356](https://frontegg.atlassian.net/browse/FR-8356) - fix country selcet width - [2962fbd4](https://github.com/frontegg/admin-box/pulls?q=2962fbd4)
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - Fix upgrading admin portal in angular and next js - [3191a16f](https://github.com/frontegg/admin-box/pulls?q=3191a16f)
> Update Frontegg AdminPortal to 5.68.3

- packages/react/package.json
- yarn.lock
- [FR-8377](https://frontegg.atlassian.net/browse/FR-8377) - fix mfa bug on speedy login - [1ea01020](https://github.com/frontegg/admin-box/pulls?q=1ea01020)
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - Fix cypress removing videos - [6ec7e647](https://github.com/frontegg/admin-box/pulls?q=6ec7e647)
> Update Frontegg AdminPortal to 5.69.0

- packages/react/package.json
- yarn.lock
- [FR-8335](https://frontegg.atlassian.net/browse/FR-8335) - fix missing expires in - [efbc845d](https://github.com/frontegg/admin-box/pulls?q=efbc845d)
- [FR-8363](https://frontegg.atlassian.net/browse/FR-8363) - dummy commit - [9568ea5a](https://github.com/frontegg/admin-box/pulls?q=9568ea5a)
> Update Frontegg AdminPortal to 5.71.0

- packages/react/package.json
- yarn.lock
- [FR-8372](https://frontegg.atlassian.net/browse/FR-8372) - admin portal events - [ee54f7c6](https://github.com/frontegg/admin-box/pulls?q=ee54f7c6)
- [FR-8383](https://frontegg.atlassian.net/browse/FR-8383) - Downgrade and Upgrade Allow Conditions - [c40ae6f2](https://github.com/frontegg/admin-box/pulls?q=c40ae6f2)
> Update Frontegg AdminPortal to 5.73.0

- packages/react/package.json
- yarn.lock
- [FR-8372](https://frontegg.atlassian.net/browse/FR-8372) - fix admin portal events - [b1eefe0a](https://github.com/frontegg/admin-box/pulls?q=b1eefe0a)
- [FR-8498](https://frontegg.atlassian.net/browse/FR-8498) - Remove invitelink invite button - [8776d7c5](https://github.com/frontegg/admin-box/pulls?q=8776d7c5)
> Update Frontegg AdminPortal to 5.74.0

- packages/react/package.json
- yarn.lock
- [FR-8560](https://frontegg.atlassian.net/browse/FR-8560) - Bump jsdom from 16.4.0 to 16.7.0 - [4cc3eaf8](https://github.com/frontegg/admin-box/pulls?q=4cc3eaf8)
- [FR-8559](https://frontegg.atlassian.net/browse/FR-8559) - Bump moment from 2.29.2 to 2.29.4 - [d26bd03d](https://github.com/frontegg/admin-box/pulls?q=d26bd03d)
- [FR-8378](https://frontegg.atlassian.net/browse/FR-8378) - Bump terser from 4.8.0 to 4.8.1 - [005b0961](https://github.com/frontegg/admin-box/pulls?q=005b0961)
- [FR-8355](https://frontegg.atlassian.net/browse/FR-8355) - added new - shorter text option for devices that remember mfa - [64e56c1a](https://github.com/frontegg/admin-box/pulls?q=64e56c1a)
> Update Frontegg AdminPortal to 5.74.1

- packages/react/package.json
- yarn.lock
- [FR-8562](https://frontegg.atlassian.net/browse/FR-8562) - Bump eventsource from 1.0.7 to 1.1.2 - [d356308c](https://github.com/frontegg/admin-box/pulls?q=d356308c)
> Update Frontegg AdminPortal to 5.75.0

- packages/react/package.json
- yarn.lock
- [FR-8652](https://frontegg.atlassian.net/browse/FR-8652) - added support for additional params on hosted login - [49000139](https://github.com/frontegg/admin-box/pulls?q=49000139)
- [FR-8477](https://frontegg.atlassian.net/browse/FR-8477) - disclaimer checkbox change formik implementation - [d174eef3](https://github.com/frontegg/admin-box/pulls?q=d174eef3)
- [FR-8355](https://frontegg.atlassian.net/browse/FR-8355) - fixed mfaRememberThisDevice text - [84175713](https://github.com/frontegg/admin-box/pulls?q=84175713)
> Update Frontegg AdminPortal to 5.76.0

- packages/react/package.json
- yarn.lock
- [FR-0000](https://frontegg.atlassian.net/browse/FR-0000) - session management hotfix - [0120fefe](https://github.com/frontegg/admin-box/pulls?q=0120fefe)
- [FR-8738](https://frontegg.atlassian.net/browse/FR-8738) - Update CODEOWNERS to all developers writing in admin box - [8ce8c5a9](https://github.com/frontegg/admin-box/pulls?q=8ce8c5a9)
- [FR-8679](https://frontegg.atlassian.net/browse/FR-8679) - fix pii data on local storage - [372fe746](https://github.com/frontegg/admin-box/pulls?q=372fe746)
> Update Frontegg AdminPortal to 5.78.0

- packages/react/package.json
- yarn.lock
- [FR-7974](https://frontegg.atlassian.net/browse/FR-7974) - invite links fix - [0c15d009](https://github.com/frontegg/admin-box/pulls?q=0c15d009)
> Update Frontegg AdminPortal to 5.79.0

- packages/react/package.json
- yarn.lock
- [FR-8795](https://frontegg.atlassian.net/browse/FR-8795) - add api hide sign up form fields - [07bcc128](https://github.com/frontegg/admin-box/pulls?q=07bcc128)
- [FR-8774](https://frontegg.atlassian.net/browse/FR-8774) - Fixes for social login refactor - [d68c293b](https://github.com/frontegg/admin-box/pulls?q=d68c293b)
> Update Frontegg AdminPortal to 5.80.1

- packages/react/package.json
- yarn.lock
- [FR-8499](https://frontegg.atlassian.net/browse/FR-8499) - Return sessionManagement feature to AdminBox - [5060c6ac](https://github.com/frontegg/admin-box/pulls?q=5060c6ac)
> Update Frontegg AdminPortal to 5.80.2

- packages/demo-saas/package.json
- packages/react/package.json
- yarn.lock
- [FR-8221](https://frontegg.atlassian.net/browse/FR-8221) - Add current version to wait for cdn - [9dd731dc](https://github.com/frontegg/admin-box/pulls?q=9dd731dc)
- [FR-8221](https://frontegg.atlassian.net/browse/FR-8221) - fix versioning in lerna - [f93fef49](https://github.com/frontegg/admin-box/pulls?q=f93fef49)
- [FR-7960](https://frontegg.atlassian.net/browse/FR-7960) - fix current session - [0940a645](https://github.com/frontegg/admin-box/pulls?q=0940a645)
- [FR-8903](https://frontegg.atlassian.net/browse/FR-8903) - add infrastructure to customization testing - [30b691af](https://github.com/frontegg/admin-box/pulls?q=30b691af)
> Update Frontegg AdminPortal to 6.2.0

- packages/react/package.json
- yarn.lock
- [FR-8221](https://frontegg.atlassian.net/browse/FR-8221) - Update cdnVersion  after increment - [041b72f4](https://github.com/frontegg/admin-box/pulls?q=041b72f4)
> Update Frontegg AdminPortal to 6.2.1

- packages/react/package.json
- yarn.lock
- [FR-8221](https://frontegg.atlassian.net/browse/FR-8221) - Fix bugs in dashboard builder mode - [b2af8970](https://github.com/frontegg/admin-box/pulls?q=b2af8970)
> Update Frontegg AdminPortal to 6.2.2

- packages/react/package.json
- yarn.lock
- [FR-8413](https://frontegg.atlassian.net/browse/FR-8413) - fix adminBox tab permissions - [5d98601a](https://github.com/frontegg/admin-box/pulls?q=5d98601a)
> Update Frontegg AdminPortal to 6.2.3

- packages/react/package.json
- yarn.lock
- [FR-8882](https://frontegg.atlassian.net/browse/FR-8882) - Make sure to show touch id in speedy login on the builder preview for all users - [eb36dc64](https://github.com/frontegg/admin-box/pulls?q=eb36dc64)
- [FR-8956](https://frontegg.atlassian.net/browse/FR-8956) - fix user management permissions - [417ed973](https://github.com/frontegg/admin-box/pulls?q=417ed973)
> Update Frontegg AdminPortal to 6.2.4

- packages/react/package.json
- yarn.lock
- [FR-8221](https://frontegg.atlassian.net/browse/FR-8221) - fix renderer issue in dashboard builder - [cef2fe7b](https://github.com/frontegg/admin-box/pulls?q=cef2fe7b)
- [FR-8879](https://frontegg.atlassian.net/browse/FR-8879) - RTL Support - [0d345d73](https://github.com/frontegg/admin-box/pulls?q=0d345d73)
- [FR-8920](https://frontegg.atlassian.net/browse/FR-8920) - test plan structure for admin portal - [62844835](https://github.com/frontegg/admin-box/pulls?q=62844835)
> Update Frontegg AdminPortal to 6.3.0

- packages/react/package.json
- yarn.lock
- [FR-8921](https://frontegg.atlassian.net/browse/FR-8921) - test plan for login box - [cc128ca1](https://github.com/frontegg/admin-box/pulls?q=cc128ca1)
- [FR-7615](https://frontegg.atlassian.net/browse/FR-7615) - Fix Permissions for viewing API tokens - [d5cc58dd](https://github.com/frontegg/admin-box/pulls?q=d5cc58dd)
> Update Frontegg AdminPortal to 6.4.0

- packages/react/package.json
- yarn.lock
- [FR-9063](https://frontegg.atlassian.net/browse/FR-9063) - white label mode for admin portal is not working on hosted login - [09f82365](https://github.com/frontegg/admin-box/pulls?q=09f82365)
> Update Frontegg AdminPortal to 6.5.0

- packages/react/package.json
- yarn.lock
- [FR-9085](https://frontegg.atlassian.net/browse/FR-9085) - fix hash routing - [73ce3b18](https://github.com/frontegg/admin-box/pulls?q=73ce3b18)
> Update Frontegg AdminPortal to 6.6.0

- packages/react/package.json
- yarn.lock
- [FR-9085](https://frontegg.atlassian.net/browse/FR-9085) - fix hash routing - [01b308ef](https://github.com/frontegg/admin-box/pulls?q=01b308ef)
> Update Frontegg AdminPortal to 6.6.1

- packages/react/package.json
- yarn.lock
- [FR-8269](https://frontegg.atlassian.net/browse/FR-8269) - update document title when visiting auth routes - [f7bac4ba](https://github.com/frontegg/admin-box/pulls?q=f7bac4ba)
- [FR-8930](https://frontegg.atlassian.net/browse/FR-8930) - ip restrictions - [3f38c464](https://github.com/frontegg/admin-box/pulls?q=3f38c464)
- [FR-8691](https://frontegg.atlassian.net/browse/FR-8691) - fix he - [9ae5d8a1](https://github.com/frontegg/admin-box/pulls?q=9ae5d8a1)
- [FR-8691](https://frontegg.atlassian.net/browse/FR-8691) - fix login mfa text - [1c8a68ac](https://github.com/frontegg/admin-box/pulls?q=1c8a68ac)
> Update Frontegg AdminPortal to 6.8.0

- packages/react/package.json
- yarn.lock
- [FR-9147](https://frontegg.atlassian.net/browse/FR-9147) - Make sure to not set doc title if login box rendered in builder mode - [6734f56c](https://github.com/frontegg/admin-box/pulls?q=6734f56c)
> Update Frontegg AdminPortal to 6.8.2

- packages/react/package.json
- yarn.lock
- [FR-9157](https://frontegg.atlassian.net/browse/FR-9157) - Display an alert when the user has not provided base url option - [5686fa47](https://github.com/frontegg/admin-box/pulls?q=5686fa47)
- [FR-9153](https://frontegg.atlassian.net/browse/FR-9153) - make sure to clear interval and event listener router - [f278bc9b](https://github.com/frontegg/admin-box/pulls?q=f278bc9b)
- [FR-9151](https://frontegg.atlassian.net/browse/FR-9151) - Render github button label as GitHub instead of Github - [9bfb4f15](https://github.com/frontegg/admin-box/pulls?q=9bfb4f15)
> Update Frontegg AdminPortal to 6.9.0

- packages/react/package.json
- yarn.lock
- [FR-9119](https://frontegg.atlassian.net/browse/FR-9119) - add api show terms and conditions in activate account - [d13ce32c](https://github.com/frontegg/admin-box/pulls?q=d13ce32c)
- [FR-9166](https://frontegg.atlassian.net/browse/FR-9166) - add future test plan sso and subscription - [69221469](https://github.com/frontegg/admin-box/pulls?q=69221469)
> Update Frontegg AdminPortal to 6.9.1

- packages/react/package.json
- yarn.lock
- [FR-7960](https://frontegg.atlassian.net/browse/FR-7960) - missing deps in location cell - [9c07483c](https://github.com/frontegg/admin-box/pulls?q=9c07483c)
> Update Frontegg AdminPortal to 6.10.0

- packages/react/package.json
- yarn.lock
- 
- [FR-9168](https://frontegg.atlassian.net/browse/FR-9168) - Add ready / loginWithRedirect - [fdfd671b](https://github.com/frontegg/admin-box/pulls?q=fdfd671b)
- [FR-8643](https://frontegg.atlassian.net/browse/FR-8643) - fix changing background color for input in preview mode - [f6429b84](https://github.com/frontegg/admin-box/pulls?q=f6429b84)
- 
- [FR-9196](https://frontegg.atlassian.net/browse/FR-9196) - Login box builder mode example app - [89e73ce2](https://github.com/frontegg/admin-box/pulls?q=89e73ce2)
- [FR-8714](https://frontegg.atlassian.net/browse/FR-8714) - recaptcha fix - [beb8081c](https://github.com/frontegg/admin-box/pulls?q=beb8081c)
> Update Frontegg AdminPortal to 6.13.0

- packages/react/package.json
- yarn.lock
- FR-9792 - fix theme chunk
- FR-9784 - pass merged palette to themes json
- FR-9777 - add option to color hover in navigation
- FR-9235 - Fix AndorrA typo in country dropdown
- FR-9725 - fix select popup
- FR-9771 - refactor toggle button
- FR-9749 - fix big titles on speedy login thumb nail mode
- FR-9730 - select tree for dark theme
- FR-9721 - add possibilities to security tabs for dark theme
- FR-9696 - fix responsiveness on builder preview
- FR-8402 - Hide sign up form when there is not local authentication same as we do in the login flow
- FR-9652 - mock flags
- FR-9667 - fix copy of restrictions
- FR-9677 - add slack provider to social login types
- FR-8849 - Resend invite and activate your account calls fix
- FR-9260 - Creating Custom webhook on the Admin Portal is sent with the …
> Update Frontegg AdminPortal to 6.45.0

- packages/react/package.json
- yarn.lock
- FR-9750 - change api according to the new names security tabs
- FR-9717 - update rest api to have optional name in add user payload - and make sure to not send name if not exist
- FR-9826 - fix table header in dark theme
- FR-9237 - Max length for secret fields increased to 100 
- FR-9742 - enroll mfa list
- FR-9772 - Send NULL on profilePictureUrl rather than null
- FR-9717 - Invite user customize form API
- FR-9597 - Webhooks - missing validation error on UI when added not allowed URL
> Update Frontegg AdminPortal to 6.46.0

- packages/react/package.json
- yarn.lock
- FR-9852 - copy invite link fix
- FR-9858 - fix - appearance and settings should be optional for invite user customization
- FR-9852 - Support copy invite link for dynamic base URL as well (mainly for Next.js)
- FR-9742 - login with mfa
- FR-9520 - FR-9504 - fonts improvements
> Update Frontegg AdminPortal to 6.48.0

- packages/react/package.json
- yarn.lock
- FR-9914 - Move initial api calls to NextJS server-side before the first render
- FR-9887 - OTC digits are not visible on mobile devices
- FR-9860 - mfa devices management
- FR-9418 - invite email bulk
> Update Frontegg AdminPortal to 6.49.0

- packages/react/package.json
- yarn.lock
- FR-10024 - fix bulk
- FR-10072 - mobile fixes for mfa
- FR-9821 - enable scim without roles
- FR-10010 - mfa fixes
- FR-10028 - fix menu for dark
- FR-10010 - card list item on click fix
- FR-10020 - add api navigation icon
- FR-10016 - mfa tests
- FR-9731 - add apple social login types
- FR-9936 - Hide Invoices on FronteggAppOptions
> Update Frontegg AdminPortal to 6.52.0

- packages/react/package.json
- yarn.lock
- FR-10162 - added support for google one tap
- FR-9983 - Improve digits component
- FR-9987 - fix social btns UI
- FR-9413 - Login, unified behaviour
> Update Frontegg AdminPortal to 6.55.0

- packages/react/package.json
- yarn.lock
- FR-10448 - add prettier pre-commit check 
- FR-10443 - Fix impersonation
- FR-10282 - fix otc login for mobile
- FR-10410 - fix policies mock
- FR-10371 - sync vendor security policies
- FR-10302 - Add impersonation indication for audit logs
- FR-10281 - Impersonation
> Update Frontegg AdminPortal to 6.66.0

- packages/react/package.json
- yarn.lock
- FR-10485 - Update `@frontegg/rest-api` version
- FR-10017 - Add `type="email"` to all email HTML inputs
- FR-10501 - Expand LoginBox width in mobile devices
- FR-10196 - Fix scroll in privacy page
- FR-10489 - UI enhancements in SCIM
- FR-10483 - Added the option to customize forget password button
- FR-10374 - UI enhancements in split mode
- FR-10184 - Add access tokens screen
- FR-9995 - UI enhancements for Invitation text and icon
> Update Frontegg AdminPortal to 6.68.0

- packages/react/package.json
- yarn.lock
- FR-11065 - add passkeys mock ff
- FR-11189 - mfa authenticator app change input type
- FR-10821 - fix table color
- FR-11204 - add unit testing with jest
- FR-11139 - fix groups
- FR-11039 - fix groups dummy
- FR-11039 - ff groups
- FR-10530 - fix ff store name
- FR-11067 - error handling on profile image upload
- FR-11039 - extend users table with groups column
- FR-10530 - fix ff
- FR-10654 - Fix OIDC loading screen
- FR-10530 - fix ff store name
- FR-10530 - fix ff store name
- FR-10530 - change ff behavior
> Update Frontegg AdminPortal to 6.82.0

- packages/react/package.json
- yarn.lock
- FR-11333 - fix tooltips
- FR-11335 - remove autofill
- FR-11106 - fix bug preview
- FR-11283 - fix passkeys autofill
- FR-11232 - tests groups
- FR-11283 - add passkeys autofill
- FR-11096 - SCIM groups
- FR-11240 - passkeys text and style changes
- FR-11042 - Fixing text across login-box - grammar and terminology
- FR-10734 - Show impersonator that they're in an impersonation session
> Update Frontegg AdminPortal to 6.84.0

- packages/react/package.json
- yarn.lock
- FR-11389 - Add js-sha256 library to test suites
- FR-11389 - Add support for generate code challenge in non-secure domains [HostedLogin Mode]
- FR-9359 - cannot update sso group name
- FR-11076 - Add live SSO integration guide
> Update Frontegg AdminPortal to 6.86.0

- packages/react/package.json
- yarn.lock
- FR-11393 - Extract customization options from App.tsx for better usage
- FR-11063 - add tests for passkeys
- FR-11351 - preserve query params for login per tenant
> Update Frontegg AdminPortal to 6.88.0

- packages/react/package.json
- yarn.lock
- FR-11419 - Lock reduxjs/toolkit version to be compatible in vite types plugin
- FR-11447 - Fix password placeholder in the login
- FR-11437 - Login Box - Fix social buttons order
- FR-11389 - Fix Vite js-sha256 warning
- FR-11420 - fix company name error in split mode sign up
- FR-11338 - fix phone number dropdown theming
- FR-11375 - a11y add aria labels
> Update Frontegg AdminPortal to 6.89.0

- packages/react/package.json
- yarn.lock
- FR-11561 - move passkeys button out of form
- FR-11538 - support-next-js-serach-param-for-login-per-tenant 
- FR-11337 - Passkeys is missing in the full Preview mode in the Builder
- FR-10976 - allow to load frontegg helper by a query param to the URL
- [Snyk] Security upgrade webpack from 5.74.0 to 5.76.0
> Update Frontegg AdminPortal to 6.93.0

- packages/react/package.json
- yarn.lock
- FR-11442 - multiple sso cleanup
- FR-11657 - login per tenant api new
- FR-11718 - fix users table
- FR-11113 - fix frontegg logo bug
- FR-11442 - SSO and provisioning split
- FR-11617 - a11y fix enter key issue
- FR-11656 - login per tenant self service UI
- FR-11352 - nested table
- [Snyk] Security upgrade @azure/storage-blob from 12.11.0 to 12.13.0
> Update Frontegg AdminPortal to 6.96.0

- packages/react/package.json
- yarn.lock
- FR-11735 - login per tenant self service dependence fix
- FR-11442 - remove admin provisioning feature flag
- FR-11723 - bump rest api version
- FR-11735 - login per tenant self service input logo upload and fixes
> Update Frontegg AdminPortal to 6.97.0

- packages/react/package.json
- yarn.lock
- FR-11769 - change source to enum
- FR-11769 - add source header to request
- FR-11658 - create mock login preview for login per tenant self service mock
- FR-11652 - SSO Guides enhancements
- [Snyk] Security upgrade babel-plugin-module-resolver from 4.1.0 to 5.0.0
> Update Frontegg AdminPortal to 6.98.0

- packages/react/package.json
- yarn.lock
- FR-11887 - bump rest api
- FR-11887 - entitlements load and hook
- FR-11600 - better error handling for login fixes
- FR-10891 - add required to fields in invite user modal
- FR-11985 - SSO Guides fixes
- FR-11600 - better error handling for login
- FR-11651 - msp all accounts state
> Update Frontegg AdminPortal to 6.103.0

- packages/react/package.json
- yarn.lock
- FR-12159 - msp bug fix
- FR-12221 - support both null and props for custom components
- FR-12159 - msp all accounts bugfix
- FR-12115 - sso guides crash unless acs url is specified
- FR-12225 - fix appearance saml and OIDC according to vendor configuration
- FR-12221 - support props and frontegg hooks in custom components
- FR-12146 - bugfix msp all accounts
- FR-12201 - dont send redirect uri on OIDC callback
- FR-12187 - FR-12188 - fix login per tenant embedded with sub domain logout route
- FR-11842 - navigation metadata msp
- FR-11887 - load ff before entitlements and prevent load for logged out users
- FR-11842 - msp single account view
- FR-11971 - implement breached password ui
> Update Frontegg AdminPortal to 6.106.0

- packages/react/package.json
- yarn.lock
- FR-12313 - Update rest api
- FR-12277 - Refactor admin portal to use active tenant
> Update Frontegg AdminPortal to 6.111.0

- packages/react/package.json
- yarn.lock
- FR-12114 - Shouldn't show inactive custom social login provider
- FR-12098 - FR-12020 - admin portal user status update if email verification is off + blinking workspace title in admin portal vivid theme
- FR-12660 - implement sagas for security center admin portal
- FR-12664 - Rename redux-saga file to prevent loop imports by webpack
- FR-12652 - init new security page. wrap with ff
- FR-12628 - fix custom login with hosted oauth in URL 
- FR-12536 - check up card component
- FR-12535 - security severity badge component
- FR-12543 - msp fix bulk users invitation
- FR-12575 - change remember my device default value
- FR-12550 - Align all auth methods to get login response of me and tenants from auth APIs
- FR-12313 - fix cdn nextjs alpha version
> Update Frontegg AdminPortal to 6.120.0

- packages/react/package.json
- yarn.lock
- FR-12696 - Entitlements redesign
- FR-12537 - recomendations component
- FR-12675 - add security center context holder and mappers for recommendations&#x2F;insights
- FR-12703 - Make sure to update correctly the change log in wrappers
- FR-12688 - Make Admin box compatible with the updated type of IUserProfile
- FR-12649 - Added a skeleton for the new security center page
> Update Frontegg AdminPortal to 6.123.0

- packages/react/package.json
- yarn.lock
- FR-12780 - Entitlements Vanilla JS improvements
- FR-12539 - security score component
- FR-12699 - implement mfa inner page for security center
- FR-12224 - replace admin portal public endpoint
> Update Frontegg AdminPortal to 6.125.0

- packages/react/package.json
- yarn.lock
- FR-11857 - Added new support for hosted login to load user on load
- 
- FR-12855 - add sso recommendation
- FR-12942 - Fix next-js build with middleware file
- FR-12291 - msp change text
- FR-12818 - Handle permissions in the security center inner pages and modified the security center main page
- FR-12859 - Pipeline - fixed lerna version for the set alpha version step in the pipeline
> Update Frontegg AdminPortal to 6.131.0

- packages/react/package.json
- yarn.lock
- FR-13142 - Support setRootAccountData action for all account feature 
- FR-12321 - Added max validations to session management fields 
- FR-12974 - Fixed the issue with permissions and roles granted from user groups on User context
- FR-12322 - Change redirect to SSO text
- FR-12979 - Fixed MFA options save button to be disabled if the user has no security write permission
> Update Frontegg AdminPortal to 6.137.0

- packages/react/package.json
- yarn.lock
- Releasing the new Security Center Page, which will replace the current Security Page. Currently exposed on Early Access with limited availability by a feature flag.
> Update Frontegg AdminPortal to 6.138.0

- packages/react/rollup.config.js
- packages/react/src/AlwaysRenderInProvider.tsx
- packages/react/src/FronteggProvider.tsx
Dev success reported that `includeQueryParam: true` is not working after signup and used to work in older versions.
After digging deeper, I discovered that this bug is unrelated to `includeQueryParam`.
The reason we keep the query param after sign-up is because of `queryKeeper` hook in the react SDK.
The reason for the bug was that we removed the logic of query keeper into the provider. Therefore it won't be called on the login page because the provider hides the children if the user is not authenticated.
1. Remove `QueryKeeperWrapper` to be under `alwaysVisibleChildren` to make it work as before 66dfe7f343d353777326764e6fcb7c3eab44bfce
2. Refactor alwaysVisibleChildren to different component c8723c3851ce9f097b4594609f33ce0284d5de53 …
> FR-13417 - Fixed include query param after signup

- packages/react/package.json
- yarn.lock
- FR-13527 - Added a11y support for admin portal pages: sso, security, profile, personal tokens, users, groups, provisioning, audit logs, api tokens, webhooks, account details.
> Update Frontegg AdminPortal to 6.157.0

- packages/react/package.json
- yarn.lock
- FR-10692 - Remove the ability to select a full category on webhooks page
> Update Frontegg AdminPortal to 6.161.0

- packages/react/package.json
- yarn.lock
- **FR-14855**: Added an option to enable `promptConsent` within `authOptions`.
- **FR-14855**: Fixed the Microsoft social login prompt value for custom configurations.
- **FR-15126**: Resolved issues with the MSP invite user dialog.
- **FR-15015**: Introduced a search bar for roles.
- **FR-12954**: Enabled Storybook publishing to CDN by branch and version, set up Storybook controls, and implemented infrastructure changes.
- **FR-11923**: Expanded the Jest unit testing environment and added more tests.
> Update Frontegg AdminPortal to 6.179.0

- packages/react/package.json
- yarn.lock
- FR-15124 - Store redirectUri before social-login as oauth2 state and restore it after successfully redirect
- FR-16117 - avoid showing apps without name in users table
- FR-16165 - Added switch tenant functionality for VanillaJS SDK
> Update Frontegg AdminPortal to 6.192.0

- packages/react/package.json
- yarn.lock
- FR-16881 - Fixed hosted login redirect url when using basename
- FR-16812 - Fixed dark theme disabled input palette
> Update Frontegg AdminPortal to 6.201.0

- packages/react/package.json
- yarn.lock
- FR-18427 - Added Support for triggering MFA after native passkeys &#x2F; iOS apple login
- FR-18211 - Fixed email overlapping roles field
> Update Frontegg AdminPortal to 7.15.0

- packages/react/package.json
- yarn.lock
- FR-18594 - Fixed blinking bug On IP and domain page
- FR-18499 - Fixed otc page blink
- FR-18005 - Fixed search api tokens with null descriptions 
- FR-18499 - Fixed activate with code and password
- FR-18582 - Fixed loader size and wrong massage
> Update Frontegg AdminPortal to 7.28.0

- packages/react/package.json
- yarn.lock
- FR-18699 - Removed entitlements automatic 30 seconds refresh mechanism
- FR-18138 - Added logic to improve login box and admin portal stability and resiliency
> Update Frontegg AdminPortal to 7.33.0

- packages/react/package.json
- yarn.lock
- FR-19547 - Added prestep support for auth flows
- FR-19048 - Changed sign-up with 6 digit code flow
- FR-19626 - Added support for social login eventually style
- FR-9045 - Fixed login form placeholder color
> Update Frontegg AdminPortal to 7.54.0

- packages/react/package.json
- yarn.lock
- FR-20267 - Added support for direction by metadata
- FR-20250 - Fixed min optional tests on password strength
- FR-19976 - Fixed pre step shouldn&#39;t appear when shouldSetPassword is not false
> Update Frontegg AdminPortal to 7.66.0

- packages/react/package.json
- yarn.lock
- FR-18986 - Added tooltip functionality for individual chips in GroupsChipsList component
- FR-20385 - Fixed user impersonation with identifiers
- FR-20254 - Added localizations for activate with social logins
- FR-20280 - Added support for signup with phone number
> Update Frontegg AdminPortal to 7.67.0

- packages/react/package.json
- yarn.lock
- FR-20862 - Fixed useLoginHint and add tests to simulate hosted prelogin flow
- FR-21121 - Added reset password with email&#x2F;sms actions and a Forgot password sms otc page 
- FR-21097 - Added suspense to renderCMCComponent
- FR-21120 - Added BaseOTC component and use it in login otc flows
- FR-21112 - Added password recovery selector and a determinePasswordRecoveryStrategy function
- FR-21118 - Fixed default language handle
- FR-20838 - Added search functionality to roles popper
- FR-20178 - Added generic IdentifierField and used it in login and forgot password flows
- FR-20945 - Added username in profile
- FR-20868 - Added usernames
> Update Frontegg AdminPortal to 7.76.0

- packages/react/package.json
- yarn.lock
- FR-21351 - Changed user loading methods to use the new V3 API
- FR-21350 - Added usage for tenant-application access types in hosted Admin box
> Update Frontegg AdminPortal to 7.81.0
